package volume

const (
	// LabelAutoGenerated is the name of the label used to tag autogenerated volumes with.
	LabelAutoGenerated = "net.oasis.volume.auto_generated"

	// LabelRuntimeID is the name of the label used to store the runtime ID.
	LabelRuntimeID = "net.oasis.volume.runtime_id"

	// LabelComponentID is the name of the label used to store the component ID.
	LabelComponentID = "net.oasis.volume.component_id"

	// LabelName is the name of the label used to store the volume name.
	LabelName = "net.oasis.volume.name"
)
