# GoReleaser configuration file.
#
# For more info, browse to http://goreleaser.com.
#
# NOTE: The GoReleaser is not meant to be run directly, but rather through
# Make's release-build target.

project_name: Oasis Core

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - id: oasis-node
    main: ./oasis-node/main.go
    binary: oasis-node
    dir: go/
    flags:
      - -trimpath
      # Build oasis-node with jemalloc tag (used by badgerdb).
      # TODO: Use 'tags' attribute when GoReleaser is udpated to newer version:
      # https://github.com/goreleaser/goreleaser/pull/2268
      - -tags=jemalloc
    ldflags:
      # NOTE: At the moment, GoReleaser produces different binaries when
      # releases are built from different git paths, unless -buildid= is added
      # to ldflags.
      # For more details, see: https://github.com/oasislabs/goreleaser/issues/1.
      - -buildid=
      - "{{.Env.GOLDFLAGS_VERSION}}"
    goos:
      - linux
    goarch:
      - amd64

  - id: oasis-net-runner
    main: ./oasis-net-runner/net-runner.go
    binary: oasis-net-runner
    dir: go/
    flags:
      - -trimpath
    ldflags:
      # NOTE: At the moment, GoReleaser produces different binaries when
      # releases are built from different git paths, unless -buildid= is added
      # to ldflags.
      # For more details, see: https://github.com/oasislabs/goreleaser/issues/1.
      - -buildid=
      - "{{.Env.GOLDFLAGS_VERSION}}"
    goos:
      - linux
    goarch:
      - amd64

  - id: oasis-remote-signer
    main: ./oasis-remote-signer/main.go
    binary: oasis-remote-signer
    dir: go/
    flags:
      - -trimpath
    ldflags:
      # NOTE: At the moment, GoReleaser produces different binaries when
      # releases are built from different git paths, unless -buildid= is added
      # to ldflags.
      # For more details, see: https://github.com/oasislabs/goreleaser/issues/1.
      - -buildid=
      - "{{.Env.GOLDFLAGS_VERSION}}"
    goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{replace .ProjectName \" \" \"_\" | tolower}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    wrap_in_directory: true
    files:
      - CHANGELOG.md
      - README.md
      - LICENSE
      # NOTE: We assume that the Makefile release-build target prepares this binary.
      - oasis-core-runtime-loader

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

snapshot:
  name_template: "{{.Version}}-dev"

release:
  name_template: "{{.ProjectName}} {{.Version}}"
