// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/storage.proto

package storage // import "github.com/oasislabs/ekiden/go/grpc/storage"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetBatchRequest struct {
	Ids                  [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBatchRequest) Reset()         { *m = GetBatchRequest{} }
func (m *GetBatchRequest) String() string { return proto.CompactTextString(m) }
func (*GetBatchRequest) ProtoMessage()    {}
func (*GetBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{2}
}
func (m *GetBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBatchRequest.Unmarshal(m, b)
}
func (m *GetBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBatchRequest.Marshal(b, m, deterministic)
}
func (dst *GetBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBatchRequest.Merge(dst, src)
}
func (m *GetBatchRequest) XXX_Size() int {
	return xxx_messageInfo_GetBatchRequest.Size(m)
}
func (m *GetBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBatchRequest proto.InternalMessageInfo

func (m *GetBatchRequest) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetBatchResponse struct {
	Data                 [][]byte `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBatchResponse) Reset()         { *m = GetBatchResponse{} }
func (m *GetBatchResponse) String() string { return proto.CompactTextString(m) }
func (*GetBatchResponse) ProtoMessage()    {}
func (*GetBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{3}
}
func (m *GetBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBatchResponse.Unmarshal(m, b)
}
func (m *GetBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBatchResponse.Marshal(b, m, deterministic)
}
func (dst *GetBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBatchResponse.Merge(dst, src)
}
func (m *GetBatchResponse) XXX_Size() int {
	return xxx_messageInfo_GetBatchResponse.Size(m)
}
func (m *GetBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBatchResponse proto.InternalMessageInfo

func (m *GetBatchResponse) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetReceiptRequest struct {
	Ids                  [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReceiptRequest) Reset()         { *m = GetReceiptRequest{} }
func (m *GetReceiptRequest) String() string { return proto.CompactTextString(m) }
func (*GetReceiptRequest) ProtoMessage()    {}
func (*GetReceiptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{4}
}
func (m *GetReceiptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReceiptRequest.Unmarshal(m, b)
}
func (m *GetReceiptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReceiptRequest.Marshal(b, m, deterministic)
}
func (dst *GetReceiptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReceiptRequest.Merge(dst, src)
}
func (m *GetReceiptRequest) XXX_Size() int {
	return xxx_messageInfo_GetReceiptRequest.Size(m)
}
func (m *GetReceiptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReceiptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReceiptRequest proto.InternalMessageInfo

func (m *GetReceiptRequest) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetReceiptResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReceiptResponse) Reset()         { *m = GetReceiptResponse{} }
func (m *GetReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*GetReceiptResponse) ProtoMessage()    {}
func (*GetReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{5}
}
func (m *GetReceiptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReceiptResponse.Unmarshal(m, b)
}
func (m *GetReceiptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReceiptResponse.Marshal(b, m, deterministic)
}
func (dst *GetReceiptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReceiptResponse.Merge(dst, src)
}
func (m *GetReceiptResponse) XXX_Size() int {
	return xxx_messageInfo_GetReceiptResponse.Size(m)
}
func (m *GetReceiptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReceiptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReceiptResponse proto.InternalMessageInfo

func (m *GetReceiptResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type InsertRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Expiry               uint64   `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertRequest) Reset()         { *m = InsertRequest{} }
func (m *InsertRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()    {}
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{6}
}
func (m *InsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRequest.Unmarshal(m, b)
}
func (m *InsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRequest.Marshal(b, m, deterministic)
}
func (dst *InsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRequest.Merge(dst, src)
}
func (m *InsertRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRequest.Size(m)
}
func (m *InsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRequest proto.InternalMessageInfo

func (m *InsertRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InsertRequest) GetExpiry() uint64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type InsertResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertResponse) Reset()         { *m = InsertResponse{} }
func (m *InsertResponse) String() string { return proto.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()    {}
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{7}
}
func (m *InsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertResponse.Unmarshal(m, b)
}
func (m *InsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertResponse.Marshal(b, m, deterministic)
}
func (dst *InsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertResponse.Merge(dst, src)
}
func (m *InsertResponse) XXX_Size() int {
	return xxx_messageInfo_InsertResponse.Size(m)
}
func (m *InsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertResponse proto.InternalMessageInfo

type InsertBatchRequest struct {
	Items                []*InsertRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *InsertBatchRequest) Reset()         { *m = InsertBatchRequest{} }
func (m *InsertBatchRequest) String() string { return proto.CompactTextString(m) }
func (*InsertBatchRequest) ProtoMessage()    {}
func (*InsertBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{8}
}
func (m *InsertBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertBatchRequest.Unmarshal(m, b)
}
func (m *InsertBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertBatchRequest.Marshal(b, m, deterministic)
}
func (dst *InsertBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertBatchRequest.Merge(dst, src)
}
func (m *InsertBatchRequest) XXX_Size() int {
	return xxx_messageInfo_InsertBatchRequest.Size(m)
}
func (m *InsertBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertBatchRequest proto.InternalMessageInfo

func (m *InsertBatchRequest) GetItems() []*InsertRequest {
	if m != nil {
		return m.Items
	}
	return nil
}

type InsertBatchResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertBatchResponse) Reset()         { *m = InsertBatchResponse{} }
func (m *InsertBatchResponse) String() string { return proto.CompactTextString(m) }
func (*InsertBatchResponse) ProtoMessage()    {}
func (*InsertBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{9}
}
func (m *InsertBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertBatchResponse.Unmarshal(m, b)
}
func (m *InsertBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertBatchResponse.Marshal(b, m, deterministic)
}
func (dst *InsertBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertBatchResponse.Merge(dst, src)
}
func (m *InsertBatchResponse) XXX_Size() int {
	return xxx_messageInfo_InsertBatchResponse.Size(m)
}
func (m *InsertBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertBatchResponse proto.InternalMessageInfo

type GetKeysRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeysRequest) Reset()         { *m = GetKeysRequest{} }
func (m *GetKeysRequest) String() string { return proto.CompactTextString(m) }
func (*GetKeysRequest) ProtoMessage()    {}
func (*GetKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{10}
}
func (m *GetKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeysRequest.Unmarshal(m, b)
}
func (m *GetKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeysRequest.Marshal(b, m, deterministic)
}
func (dst *GetKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeysRequest.Merge(dst, src)
}
func (m *GetKeysRequest) XXX_Size() int {
	return xxx_messageInfo_GetKeysRequest.Size(m)
}
func (m *GetKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeysRequest proto.InternalMessageInfo

type GetKeysResponse struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Expiry               uint64   `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKeysResponse) Reset()         { *m = GetKeysResponse{} }
func (m *GetKeysResponse) String() string { return proto.CompactTextString(m) }
func (*GetKeysResponse) ProtoMessage()    {}
func (*GetKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{11}
}
func (m *GetKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKeysResponse.Unmarshal(m, b)
}
func (m *GetKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKeysResponse.Marshal(b, m, deterministic)
}
func (dst *GetKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKeysResponse.Merge(dst, src)
}
func (m *GetKeysResponse) XXX_Size() int {
	return xxx_messageInfo_GetKeysResponse.Size(m)
}
func (m *GetKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKeysResponse proto.InternalMessageInfo

func (m *GetKeysResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetKeysResponse) GetExpiry() uint64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type LogEntry struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogEntry) Reset()         { *m = LogEntry{} }
func (m *LogEntry) String() string { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()    {}
func (*LogEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{12}
}
func (m *LogEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogEntry.Unmarshal(m, b)
}
func (m *LogEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogEntry.Marshal(b, m, deterministic)
}
func (dst *LogEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogEntry.Merge(dst, src)
}
func (m *LogEntry) XXX_Size() int {
	return xxx_messageInfo_LogEntry.Size(m)
}
func (m *LogEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LogEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LogEntry proto.InternalMessageInfo

func (m *LogEntry) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *LogEntry) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type ApplyRequest struct {
	Root                 []byte      `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	ExpectedNewRoot      []byte      `protobuf:"bytes,2,opt,name=expected_new_root,json=expectedNewRoot,proto3" json:"expected_new_root,omitempty"`
	Log                  []*LogEntry `protobuf:"bytes,3,rep,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{13}
}
func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (dst *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(dst, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *ApplyRequest) GetExpectedNewRoot() []byte {
	if m != nil {
		return m.ExpectedNewRoot
	}
	return nil
}

func (m *ApplyRequest) GetLog() []*LogEntry {
	if m != nil {
		return m.Log
	}
	return nil
}

type ApplyResponse struct {
	Receipt              []byte   `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyResponse) Reset()         { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()    {}
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{14}
}
func (m *ApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse.Unmarshal(m, b)
}
func (m *ApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse.Marshal(b, m, deterministic)
}
func (dst *ApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse.Merge(dst, src)
}
func (m *ApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse.Size(m)
}
func (m *ApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse proto.InternalMessageInfo

func (m *ApplyResponse) GetReceipt() []byte {
	if m != nil {
		return m.Receipt
	}
	return nil
}

type NodeID struct {
	Path                 []byte   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Depth                uint32   `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeID) Reset()         { *m = NodeID{} }
func (m *NodeID) String() string { return proto.CompactTextString(m) }
func (*NodeID) ProtoMessage()    {}
func (*NodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{15}
}
func (m *NodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeID.Unmarshal(m, b)
}
func (m *NodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeID.Marshal(b, m, deterministic)
}
func (dst *NodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeID.Merge(dst, src)
}
func (m *NodeID) XXX_Size() int {
	return xxx_messageInfo_NodeID.Size(m)
}
func (m *NodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeID.DiscardUnknown(m)
}

var xxx_messageInfo_NodeID proto.InternalMessageInfo

func (m *NodeID) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *NodeID) GetDepth() uint32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

type GetSubtreeRequest struct {
	Root                 []byte   `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Id                   *NodeID  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MaxDepth             uint32   `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubtreeRequest) Reset()         { *m = GetSubtreeRequest{} }
func (m *GetSubtreeRequest) String() string { return proto.CompactTextString(m) }
func (*GetSubtreeRequest) ProtoMessage()    {}
func (*GetSubtreeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{16}
}
func (m *GetSubtreeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubtreeRequest.Unmarshal(m, b)
}
func (m *GetSubtreeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubtreeRequest.Marshal(b, m, deterministic)
}
func (dst *GetSubtreeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubtreeRequest.Merge(dst, src)
}
func (m *GetSubtreeRequest) XXX_Size() int {
	return xxx_messageInfo_GetSubtreeRequest.Size(m)
}
func (m *GetSubtreeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubtreeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubtreeRequest proto.InternalMessageInfo

func (m *GetSubtreeRequest) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *GetSubtreeRequest) GetId() *NodeID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *GetSubtreeRequest) GetMaxDepth() uint32 {
	if m != nil {
		return m.MaxDepth
	}
	return 0
}

type GetSubtreeResponse struct {
	Subtree              []byte   `protobuf:"bytes,1,opt,name=subtree,proto3" json:"subtree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSubtreeResponse) Reset()         { *m = GetSubtreeResponse{} }
func (m *GetSubtreeResponse) String() string { return proto.CompactTextString(m) }
func (*GetSubtreeResponse) ProtoMessage()    {}
func (*GetSubtreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{17}
}
func (m *GetSubtreeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSubtreeResponse.Unmarshal(m, b)
}
func (m *GetSubtreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSubtreeResponse.Marshal(b, m, deterministic)
}
func (dst *GetSubtreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSubtreeResponse.Merge(dst, src)
}
func (m *GetSubtreeResponse) XXX_Size() int {
	return xxx_messageInfo_GetSubtreeResponse.Size(m)
}
func (m *GetSubtreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSubtreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSubtreeResponse proto.InternalMessageInfo

func (m *GetSubtreeResponse) GetSubtree() []byte {
	if m != nil {
		return m.Subtree
	}
	return nil
}

type GetPathRequest struct {
	Root                 []byte   `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	StartDepth           uint32   `protobuf:"varint,3,opt,name=start_depth,json=startDepth,proto3" json:"start_depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPathRequest) Reset()         { *m = GetPathRequest{} }
func (m *GetPathRequest) String() string { return proto.CompactTextString(m) }
func (*GetPathRequest) ProtoMessage()    {}
func (*GetPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{18}
}
func (m *GetPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPathRequest.Unmarshal(m, b)
}
func (m *GetPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPathRequest.Marshal(b, m, deterministic)
}
func (dst *GetPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPathRequest.Merge(dst, src)
}
func (m *GetPathRequest) XXX_Size() int {
	return xxx_messageInfo_GetPathRequest.Size(m)
}
func (m *GetPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPathRequest proto.InternalMessageInfo

func (m *GetPathRequest) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *GetPathRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetPathRequest) GetStartDepth() uint32 {
	if m != nil {
		return m.StartDepth
	}
	return 0
}

type GetPathResponse struct {
	Subtree              []byte   `protobuf:"bytes,1,opt,name=subtree,proto3" json:"subtree,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPathResponse) Reset()         { *m = GetPathResponse{} }
func (m *GetPathResponse) String() string { return proto.CompactTextString(m) }
func (*GetPathResponse) ProtoMessage()    {}
func (*GetPathResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{19}
}
func (m *GetPathResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPathResponse.Unmarshal(m, b)
}
func (m *GetPathResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPathResponse.Marshal(b, m, deterministic)
}
func (dst *GetPathResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPathResponse.Merge(dst, src)
}
func (m *GetPathResponse) XXX_Size() int {
	return xxx_messageInfo_GetPathResponse.Size(m)
}
func (m *GetPathResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPathResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPathResponse proto.InternalMessageInfo

func (m *GetPathResponse) GetSubtree() []byte {
	if m != nil {
		return m.Subtree
	}
	return nil
}

type GetNodeRequest struct {
	Root                 []byte   `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Id                   *NodeID  `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{20}
}
func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(dst, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

func (m *GetNodeRequest) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *GetNodeRequest) GetId() *NodeID {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetNodeResponse struct {
	Node                 []byte   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeResponse) Reset()         { *m = GetNodeResponse{} }
func (m *GetNodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetNodeResponse) ProtoMessage()    {}
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{21}
}
func (m *GetNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeResponse.Unmarshal(m, b)
}
func (m *GetNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeResponse.Marshal(b, m, deterministic)
}
func (dst *GetNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeResponse.Merge(dst, src)
}
func (m *GetNodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetNodeResponse.Size(m)
}
func (m *GetNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeResponse proto.InternalMessageInfo

func (m *GetNodeResponse) GetNode() []byte {
	if m != nil {
		return m.Node
	}
	return nil
}

type GetValueRequest struct {
	Root                 []byte   `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	Id                   []byte   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueRequest) Reset()         { *m = GetValueRequest{} }
func (m *GetValueRequest) String() string { return proto.CompactTextString(m) }
func (*GetValueRequest) ProtoMessage()    {}
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{22}
}
func (m *GetValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueRequest.Unmarshal(m, b)
}
func (m *GetValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueRequest.Marshal(b, m, deterministic)
}
func (dst *GetValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueRequest.Merge(dst, src)
}
func (m *GetValueRequest) XXX_Size() int {
	return xxx_messageInfo_GetValueRequest.Size(m)
}
func (m *GetValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueRequest proto.InternalMessageInfo

func (m *GetValueRequest) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *GetValueRequest) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type GetValueResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetValueResponse) Reset()         { *m = GetValueResponse{} }
func (m *GetValueResponse) String() string { return proto.CompactTextString(m) }
func (*GetValueResponse) ProtoMessage()    {}
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_storage_eb0d5e8efa0a65c4, []int{23}
}
func (m *GetValueResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetValueResponse.Unmarshal(m, b)
}
func (m *GetValueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetValueResponse.Marshal(b, m, deterministic)
}
func (dst *GetValueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetValueResponse.Merge(dst, src)
}
func (m *GetValueResponse) XXX_Size() int {
	return xxx_messageInfo_GetValueResponse.Size(m)
}
func (m *GetValueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetValueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetValueResponse proto.InternalMessageInfo

func (m *GetValueResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "storage.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "storage.GetResponse")
	proto.RegisterType((*GetBatchRequest)(nil), "storage.GetBatchRequest")
	proto.RegisterType((*GetBatchResponse)(nil), "storage.GetBatchResponse")
	proto.RegisterType((*GetReceiptRequest)(nil), "storage.GetReceiptRequest")
	proto.RegisterType((*GetReceiptResponse)(nil), "storage.GetReceiptResponse")
	proto.RegisterType((*InsertRequest)(nil), "storage.InsertRequest")
	proto.RegisterType((*InsertResponse)(nil), "storage.InsertResponse")
	proto.RegisterType((*InsertBatchRequest)(nil), "storage.InsertBatchRequest")
	proto.RegisterType((*InsertBatchResponse)(nil), "storage.InsertBatchResponse")
	proto.RegisterType((*GetKeysRequest)(nil), "storage.GetKeysRequest")
	proto.RegisterType((*GetKeysResponse)(nil), "storage.GetKeysResponse")
	proto.RegisterType((*LogEntry)(nil), "storage.LogEntry")
	proto.RegisterType((*ApplyRequest)(nil), "storage.ApplyRequest")
	proto.RegisterType((*ApplyResponse)(nil), "storage.ApplyResponse")
	proto.RegisterType((*NodeID)(nil), "storage.NodeID")
	proto.RegisterType((*GetSubtreeRequest)(nil), "storage.GetSubtreeRequest")
	proto.RegisterType((*GetSubtreeResponse)(nil), "storage.GetSubtreeResponse")
	proto.RegisterType((*GetPathRequest)(nil), "storage.GetPathRequest")
	proto.RegisterType((*GetPathResponse)(nil), "storage.GetPathResponse")
	proto.RegisterType((*GetNodeRequest)(nil), "storage.GetNodeRequest")
	proto.RegisterType((*GetNodeResponse)(nil), "storage.GetNodeResponse")
	proto.RegisterType((*GetValueRequest)(nil), "storage.GetValueRequest")
	proto.RegisterType((*GetValueResponse)(nil), "storage.GetValueResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageClient interface {
	// CAS
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*GetBatchResponse, error)
	GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*GetReceiptResponse, error)
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	InsertBatch(ctx context.Context, in *InsertBatchRequest, opts ...grpc.CallOption) (*InsertBatchResponse, error)
	GetKeys(ctx context.Context, in *GetKeysRequest, opts ...grpc.CallOption) (Storage_GetKeysClient, error)
	// MKVS
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	GetSubtree(ctx context.Context, in *GetSubtreeRequest, opts ...grpc.CallOption) (*GetSubtreeResponse, error)
	GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetBatch(ctx context.Context, in *GetBatchRequest, opts ...grpc.CallOption) (*GetBatchResponse, error) {
	out := new(GetBatchResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*GetReceiptResponse, error) {
	out := new(GetReceiptResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) InsertBatch(ctx context.Context, in *InsertBatchRequest, opts ...grpc.CallOption) (*InsertBatchResponse, error) {
	out := new(InsertBatchResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/InsertBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetKeys(ctx context.Context, in *GetKeysRequest, opts ...grpc.CallOption) (Storage_GetKeysClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Storage_serviceDesc.Streams[0], "/storage.Storage/GetKeys", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageGetKeysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Storage_GetKeysClient interface {
	Recv() (*GetKeysResponse, error)
	grpc.ClientStream
}

type storageGetKeysClient struct {
	grpc.ClientStream
}

func (x *storageGetKeysClient) Recv() (*GetKeysResponse, error) {
	m := new(GetKeysResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *storageClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetSubtree(ctx context.Context, in *GetSubtreeRequest, opts ...grpc.CallOption) (*GetSubtreeResponse, error) {
	out := new(GetSubtreeResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetSubtree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error) {
	out := new(GetPathResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetPath", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, "/storage.Storage/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
type StorageServer interface {
	// CAS
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetBatch(context.Context, *GetBatchRequest) (*GetBatchResponse, error)
	GetReceipt(context.Context, *GetReceiptRequest) (*GetReceiptResponse, error)
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	InsertBatch(context.Context, *InsertBatchRequest) (*InsertBatchResponse, error)
	GetKeys(*GetKeysRequest, Storage_GetKeysServer) error
	// MKVS
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	GetSubtree(context.Context, *GetSubtreeRequest) (*GetSubtreeResponse, error)
	GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetBatch(ctx, req.(*GetBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetReceipt(ctx, req.(*GetReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_InsertBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).InsertBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/InsertBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).InsertBatch(ctx, req.(*InsertBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetKeysRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServer).GetKeys(m, &storageGetKeysServer{stream})
}

type Storage_GetKeysServer interface {
	Send(*GetKeysResponse) error
	grpc.ServerStream
}

type storageGetKeysServer struct {
	grpc.ServerStream
}

func (x *storageGetKeysServer) Send(m *GetKeysResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Storage_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetSubtree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubtreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetSubtree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetSubtree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetSubtree(ctx, req.(*GetSubtreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetPath",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetPath(ctx, req.(*GetPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.Storage/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "storage.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Storage_Get_Handler,
		},
		{
			MethodName: "GetBatch",
			Handler:    _Storage_GetBatch_Handler,
		},
		{
			MethodName: "GetReceipt",
			Handler:    _Storage_GetReceipt_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _Storage_Insert_Handler,
		},
		{
			MethodName: "InsertBatch",
			Handler:    _Storage_InsertBatch_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _Storage_Apply_Handler,
		},
		{
			MethodName: "GetSubtree",
			Handler:    _Storage_GetSubtree_Handler,
		},
		{
			MethodName: "GetPath",
			Handler:    _Storage_GetPath_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Storage_GetNode_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _Storage_GetValue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetKeys",
			Handler:       _Storage_GetKeys_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage/storage.proto",
}

func init() { proto.RegisterFile("storage/storage.proto", fileDescriptor_storage_eb0d5e8efa0a65c4) }

var fileDescriptor_storage_eb0d5e8efa0a65c4 = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xed, 0x4f, 0x1a, 0x4f,
	0x10, 0x16, 0x4e, 0xc0, 0xdf, 0x80, 0x88, 0xeb, 0x1b, 0x3f, 0x34, 0xd1, 0xae, 0xb1, 0xa1, 0xb5,
	0x85, 0x86, 0xa6, 0x49, 0x13, 0x93, 0xa6, 0x1a, 0x0d, 0xb1, 0x6d, 0x4c, 0x73, 0x26, 0x6d, 0xd2,
	0x2f, 0xe6, 0xe0, 0x26, 0x70, 0x11, 0xb8, 0xeb, 0xdd, 0x52, 0xe1, 0x5f, 0xed, 0x5f, 0xd3, 0xec,
	0xcb, 0x2d, 0xbb, 0x88, 0xf4, 0x43, 0x3f, 0xb1, 0xbb, 0xf3, 0xf2, 0x3c, 0x33, 0x37, 0xcf, 0x00,
	0x3b, 0x09, 0x0b, 0x63, 0xaf, 0x87, 0x4d, 0xf5, 0xdb, 0x88, 0xe2, 0x90, 0x85, 0xa4, 0xa0, 0xae,
	0xf4, 0x00, 0xa0, 0x8d, 0xcc, 0xc5, 0x9f, 0x63, 0x4c, 0x18, 0x29, 0x43, 0x36, 0xf0, 0xab, 0x99,
	0xa3, 0x4c, 0xbd, 0xe4, 0x66, 0x03, 0x9f, 0x3e, 0x83, 0xa2, 0xb0, 0x26, 0x51, 0x38, 0x4a, 0x90,
	0x10, 0x58, 0xf5, 0x3d, 0xe6, 0x29, 0x07, 0x71, 0xa6, 0xc7, 0xb0, 0xd1, 0x46, 0x76, 0xe1, 0xb1,
	0x6e, 0x3f, 0xcd, 0x52, 0x01, 0x27, 0xf0, 0x93, 0x6a, 0xe6, 0xc8, 0xa9, 0x97, 0x5c, 0x7e, 0xa4,
	0xcf, 0xa1, 0x32, 0x73, 0x7a, 0x94, 0xcc, 0xd1, 0xc9, 0x4e, 0x60, 0x53, 0xe0, 0x75, 0x31, 0x88,
	0xd8, 0xd3, 0xe9, 0xea, 0x40, 0x4c, 0xb7, 0x25, 0xec, 0xce, 0x60, 0xfd, 0x7a, 0x94, 0x60, 0xac,
	0x93, 0x2d, 0x70, 0x22, 0xbb, 0x90, 0xc7, 0x49, 0x14, 0xc4, 0xd3, 0x6a, 0xf6, 0x28, 0x53, 0x5f,
	0x75, 0xd5, 0x8d, 0x56, 0xa0, 0x9c, 0x06, 0x4b, 0x08, 0x7a, 0x01, 0x44, 0xbe, 0x58, 0xf5, 0xbe,
	0x82, 0x5c, 0xc0, 0x70, 0x28, 0x29, 0x16, 0x5b, 0xbb, 0x8d, 0xb4, 0xd7, 0x16, 0xb4, 0x2b, 0x9d,
	0xe8, 0x0e, 0x6c, 0x59, 0x39, 0x54, 0xea, 0x0a, 0x94, 0xdb, 0xc8, 0x3e, 0xe3, 0x34, 0x51, 0xfe,
	0xf4, 0x4c, 0x74, 0x56, 0xbe, 0xa8, 0x12, 0x2b, 0xe0, 0xdc, 0xe3, 0x54, 0x91, 0xe7, 0xc7, 0x27,
	0xb9, 0xb7, 0x60, 0xed, 0x4b, 0xd8, 0xbb, 0x1a, 0xb1, 0x78, 0xba, 0x20, 0x6a, 0x1b, 0x72, 0xbf,
	0xbc, 0xc1, 0x18, 0x45, 0x50, 0xc9, 0x95, 0x17, 0x9a, 0x40, 0xe9, 0x3c, 0x8a, 0x06, 0x53, 0xa3,
	0x57, 0x71, 0x18, 0xb2, 0xb4, 0x57, 0xfc, 0x4c, 0x5e, 0xc2, 0x26, 0x4e, 0x22, 0xec, 0x32, 0xf4,
	0xef, 0x46, 0xf8, 0x70, 0x27, 0x1c, 0x64, 0x96, 0x8d, 0xd4, 0x70, 0x83, 0x0f, 0x2e, 0xf7, 0x3d,
	0x06, 0x67, 0x10, 0xf6, 0xaa, 0x8e, 0xe8, 0xca, 0xa6, 0xee, 0x4a, 0xca, 0xcb, 0xe5, 0x56, 0xfa,
	0x02, 0xd6, 0x15, 0xa8, 0xaa, 0xb1, 0x0a, 0x85, 0x58, 0x7e, 0x59, 0x05, 0x9c, 0x5e, 0x69, 0x0b,
	0xf2, 0x37, 0xa1, 0x8f, 0xd7, 0x97, 0x9c, 0x59, 0xe4, 0xb1, 0x7e, 0xca, 0x8c, 0x9f, 0x79, 0x4d,
	0x3e, 0x46, 0xac, 0x2f, 0xd8, 0xac, 0xbb, 0xf2, 0x42, 0x51, 0x4c, 0xd4, 0xed, 0xb8, 0xc3, 0x62,
	0xc4, 0x65, 0x85, 0x1d, 0x8a, 0xd1, 0xe7, 0xb1, 0xc5, 0xd6, 0x86, 0xe6, 0x2a, 0xf1, 0xb8, 0x16,
	0xc8, 0x3e, 0xfc, 0x37, 0xf4, 0x26, 0x77, 0x12, 0xc3, 0x11, 0x18, 0x6b, 0x43, 0x6f, 0x72, 0x29,
	0x60, 0x1a, 0x62, 0x22, 0x35, 0xcc, 0xac, 0x94, 0x44, 0x3e, 0xa5, 0xa5, 0xa8, 0x2b, 0xfd, 0x2e,
	0xbe, 0xf6, 0x57, 0x8f, 0xf5, 0x97, 0x71, 0x52, 0x1f, 0x2e, 0x3b, 0xfb, 0x70, 0x87, 0x50, 0x4c,
	0x98, 0x17, 0x33, 0x8b, 0x06, 0x88, 0x27, 0x49, 0xe4, 0x54, 0x0c, 0x8d, 0x4c, 0xfc, 0x57, 0x16,
	0x57, 0x82, 0x05, 0xaf, 0xf1, 0x5f, 0x3a, 0x43, 0x4f, 0x04, 0xa6, 0x4c, 0x33, 0xd3, 0xe2, 0x28,
	0xf4, 0x53, 0x40, 0x71, 0xa6, 0xef, 0x84, 0xdb, 0x37, 0x3e, 0x6a, 0xcb, 0xe0, 0xca, 0x1a, 0x4e,
	0xee, 0xa0, 0xba, 0xd8, 0x1d, 0x2a, 0x4c, 0xa5, 0xd7, 0xf3, 0x9b, 0x31, 0xe6, 0xb7, 0xf5, 0x3b,
	0x07, 0x85, 0x5b, 0x49, 0x8f, 0xb4, 0xc0, 0x69, 0x23, 0x23, 0x5b, 0x9a, 0xef, 0x6c, 0xcb, 0xd5,
	0xb6, 0xed, 0x47, 0x25, 0xc0, 0x15, 0x72, 0x0e, 0x6b, 0xe9, 0x96, 0x22, 0x55, 0xd3, 0xc7, 0x54,
	0x7b, 0xed, 0xff, 0x05, 0x16, 0x9d, 0xa2, 0xad, 0xd6, 0xa9, 0x18, 0x58, 0x52, 0xb3, 0x81, 0xcc,
	0xad, 0x56, 0xdb, 0x5f, 0x68, 0xd3, 0x89, 0xce, 0x20, 0x2f, 0xb7, 0x04, 0x79, 0x62, 0x9d, 0xd4,
	0xf6, 0x1e, 0xbd, 0xeb, 0xe0, 0x4f, 0x50, 0x34, 0x56, 0x0c, 0xd9, 0x9f, 0xf3, 0xb4, 0xca, 0x39,
	0x58, 0x6c, 0xd4, 0xb9, 0x3e, 0x42, 0x41, 0x6d, 0x21, 0xb2, 0x67, 0x52, 0x36, 0x36, 0x55, 0xad,
	0xfa, 0xd8, 0x90, 0xc6, 0xbf, 0xc9, 0x90, 0xf7, 0x90, 0x13, 0x0a, 0x27, 0x3b, 0xda, 0xcd, 0x5c,
	0x33, 0xb5, 0xdd, 0xf9, 0xe7, 0xb9, 0x6e, 0x2a, 0x55, 0xd9, 0xdd, 0xb4, 0x15, 0x6d, 0x77, 0x73,
	0x4e, 0x86, 0x74, 0x85, 0x7c, 0x10, 0x45, 0x70, 0x55, 0xd8, 0x45, 0x18, 0x02, 0xb4, 0x8b, 0x30,
	0x05, 0xa4, 0xe3, 0xf9, 0x84, 0xdb, 0xf1, 0x86, 0x74, 0xec, 0x78, 0x53, 0x0c, 0x7a, 0xb2, 0xc4,
	0x0c, 0xdb, 0x93, 0x65, 0xaa, 0xc1, 0x9e, 0x2c, 0x6b, 0xe0, 0xe9, 0xca, 0xc5, 0xeb, 0x1f, 0xa7,
	0xbd, 0x80, 0xf5, 0xc7, 0x9d, 0x46, 0x37, 0x1c, 0x36, 0x43, 0x2f, 0x09, 0x92, 0x81, 0xd7, 0x49,
	0x9a, 0x78, 0x1f, 0xf8, 0x38, 0x6a, 0xf6, 0xc2, 0x66, 0x2f, 0x8e, 0xba, 0xe9, 0xdf, 0x7c, 0x27,
	0x2f, 0xfe, 0xe7, 0xdf, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xb8, 0x14, 0x07, 0x00, 0x08,
	0x00, 0x00,
}
