################
# Build pipeline
################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v3.0.1-oasis1:
    image: "oasislabs/testing:0.3.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - /var/lib/buildkite-agent/.ssh:/root/.ssh
      - /var/lib/buildkite-agent/.coveralls:/root/.coveralls
      - /var/lib/buildkite-agent/.codecov:/root/.codecov
      # Shared Rust incremental compile caches.
      - /tmp/cargo_ic/debug:/tmp/artifacts/debug/incremental
      - /tmp/cargo_ic/debug_sgx:/tmp/artifacts/x86_64-unknown-linux-sgx/debug/incremental
      # Shared Rust package checkouts directory.
      - /tmp/cargo_pkg/git:/root/.cargo/git
      - /tmp/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /tmp/xargo_cache:/root/.xargo
      # Shared Go package checkouts directory.
      - /tmp/go_pkg:/root/go/pkg
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/tmp/artifacts"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
      - "GOPROXY=https://athens.ops.oasiscloud.io/"
    propagate-environment: true
    unconfined: true

steps:
  ###########
  # Lint jobs
  ###########
  - label: Lint Git commits
    command: .buildkite/scripts/lint_git.sh
    plugins:
      <<: *docker_plugin_configuration

  - label: Lint Go node
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/go/lint_ekiden.sh
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Lint Rust crate versions
    command: .buildkite/rust/lint_crate_versions.sh
    plugins:
      <<: *docker_plugin_configuration

  ############
  # Build jobs
  ############
  # This label needs to be synced with runtime-ethereum's
  # .buildkite/scripts/download_common_artifacts.sh.
  - label: Build Go node
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/go/build_ekiden.sh

      # Upload the built artifacts.
      - cd /workdir/go/ekiden
      - buildkite-agent artifact upload ekiden
    plugins:
      <<: *docker_plugin_configuration

  # This label needs to be synced with runtime-ethereum's
  # .buildkite/scripts/download_common_artifacts.sh.
  - label: Build Rust runtime loader
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/rust/build_generic.sh /workdir -p ekiden-runtime-loader
      - .buildkite/rust/build_generic.sh /workdir -p test-long-term-client
      - .buildkite/rust/build_generic.sh /workdir -p simple-keyvalue-client
      - .buildkite/rust/build_generic.sh /workdir -p simple-keyvalue-enc-client

      # Upload the built artifacts.
      - cd /tmp/artifacts/debug
      - buildkite-agent artifact upload ekiden-runtime-loader
      # Clients for E2E tests.
      - buildkite-agent artifact upload test-long-term-client
      - buildkite-agent artifact upload simple-keyvalue-client
      - buildkite-agent artifact upload simple-keyvalue-enc-client
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  ####################
  # Runtime build jobs
  ####################
  # This label needs to be synced with runtime-ethereum's
  # .buildkite/rust/build_and_test_runtime.sh and .buildkite/scripts/download_common_artifacts.sh.
  - label: Build key manager runtime
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/rust/build_runtime.sh keymanager-runtime
      # The test runtime must be built here as it requires the keymanager enclave hash.
      - export KM_ENCLAVE_PATH=/tmp/artifacts/x86_64-fortanix-unknown-sgx/debug/ekiden-keymanager-runtime.sgxs
      - .buildkite/rust/build_runtime.sh tests/runtimes/simple-keyvalue

      # Upload the built artifacts.
      - cd /tmp/artifacts/x86_64-fortanix-unknown-sgx/debug
      - buildkite-agent artifact upload ekiden-keymanager-runtime.sgxs
      - buildkite-agent artifact upload simple-keyvalue.sgxs
      - cd /tmp/artifacts/debug
      - buildkite-agent artifact upload ekiden-keymanager-runtime
      - buildkite-agent artifact upload simple-keyvalue
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  ###########
  # Test jobs
  ###########
  - label: Test Rust crates
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/rust/test_generic.sh .
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  # Wait for all jobs defined before this point
  # to finish running in parallel before continuing.
  - wait

  #####################################
  # Test jobs requiring build artifacts
  #####################################
  - label: Test Go node
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/go/test_and_coverage_ekiden.sh
    plugins:
      <<: *docker_plugin_configuration

  #########################
  # Test single node config
  #########################
  - label: Test single node config
    timeout_in_minutes: 20
    command:
      - .buildkite/scripts/download_e2e_test_artifacts.sh
      - .buildkite/scripts/test_config.sh single_node
    plugins:
      <<: *docker_plugin_configuration

  ###############
  # E2E test jobs
  ###############
  - label: E2E tests (%n)
    parallelism: 2
    timeout_in_minutes: 5
    command:
      - .buildkite/scripts/download_e2e_test_artifacts.sh
      - .buildkite/scripts/test_e2e.sh
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: E2E migration tests
    timeout_in_minutes: 5
    command:
      - .buildkite/scripts/download_e2e_test_artifacts.sh
      - .buildkite/scripts/test_migration.sh
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  ####################################
  # Rust coverage job (only on master)
  ####################################

  - label: Coverage Rust crates
    branches: master
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/rust/coverage.sh
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  ##############################
  # Deploy jobs (only on master)
  ##############################

  # Wait for all jobs defined before this point
  # to finish running in parallel before continuing.
  - wait

  - label: ":rocket: Deploy image"
    trigger: ekiden-deploy-image
    async: true
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
