// This is re-exported here only so it can be used in macros under a common name.
pub use ekiden_common::futures::{BoxFuture, Future};
pub use ekiden_common::signature::Signer;
pub use ekiden_enclave_common::quote;
pub use ekiden_rpc_client::backend::RpcClientBackend;

/// Create a contract client for a given API.
///
/// # Examples
///
/// This macro should be invoked using a concrete API generated by `contract_api` as
/// follows:
/// ```
/// with_api! {
///     create_contract_client!(foo, foo_api, api);
/// }
/// ```
///
/// In this example, the generated client will be put into a module called `foo`
/// which will use API structures from module `foo_api`. The API definitions will
/// passed as the last argument as defined by the `api` token.
#[macro_export]
macro_rules! create_contract_client {
    (
        $output_module: ident,
        $api_module: path,

        $(
            pub fn $method_name: ident ( $request_type: ty ) -> $response_type: ty ;
        )*
    ) => {
        mod $output_module {
            use std::sync::Arc;

            use $crate::client::ContractClient;
            use $crate::macros::quote::MrEnclave;
            use $crate::macros::{BoxFuture, RpcClientBackend, Signer};

            pub use $api_module::*;

            pub struct Client<Backend: RpcClientBackend + 'static> {
                client: ContractClient<Backend>,
            }

            #[allow(dead_code)]
            impl<Backend: RpcClientBackend + 'static> Client<Backend> {
                /// Create new client instance.
                pub fn new(backend: Arc<Backend>,
                           mr_enclave: MrEnclave,
                           signer: Arc<Signer + Send + Sync>) -> Self {

                    Client {
                        client: ContractClient::new(
                            backend,
                            mr_enclave,
                            signer,
                        ),
                    }
                }

                // Generate methods.
                $(
                    pub fn $method_name(
                        &mut self,
                        arguments: $request_type
                    ) -> BoxFuture<$response_type> {
                        self.client.call(stringify!($method_name), arguments)
                    }
                )*
            }
        }
    };
}
