[advisories]
ignore = [
    "RUSTSEC-2023-0071", # Does not affect our current use of the library.
    "RUSTSEC-2026-0049", # Vulnerable crate is only used in simple-rofl test runtime.
    "RUSTSEC-2026-0098", # Vulnerable crate is only used in simple-rofl test runtime.
]
