// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aesm_proto.proto

package aesm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	InitQuoteReq                  *Request_InitQuoteRequest                  `protobuf:"bytes,1,opt,name=initQuoteReq" json:"initQuoteReq,omitempty"`
	GetQuoteReq                   *Request_GetQuoteRequest                   `protobuf:"bytes,2,opt,name=getQuoteReq" json:"getQuoteReq,omitempty"`
	GetLicTokenReq                *Request_GetLaunchTokenRequest             `protobuf:"bytes,3,opt,name=getLicTokenReq" json:"getLicTokenReq,omitempty"`
	ReportErrReq                  *Request_ReportAttestationErrorRequest     `protobuf:"bytes,4,opt,name=reportErrReq" json:"reportErrReq,omitempty"`
	CreateSessionReq              *Request_CreateSessionRequest              `protobuf:"bytes,5,opt,name=createSessionReq" json:"createSessionReq,omitempty"`
	InvokeServiceReq              *Request_InvokeServiceRequest              `protobuf:"bytes,6,opt,name=invokeServiceReq" json:"invokeServiceReq,omitempty"`
	ExchangeReportReq             *Request_ExchangeReportRequest             `protobuf:"bytes,7,opt,name=exchangeReportReq" json:"exchangeReportReq,omitempty"`
	CloseSessionReq               *Request_CloseSessionRequest               `protobuf:"bytes,8,opt,name=closeSessionReq" json:"closeSessionReq,omitempty"`
	GetPsCapReq                   *Request_GetPsCapRequest                   `protobuf:"bytes,9,opt,name=getPsCapReq" json:"getPsCapReq,omitempty"`
	GetWhiteListSizeReq           *Request_GetWhiteListSizeRequest           `protobuf:"bytes,10,opt,name=getWhiteListSizeReq" json:"getWhiteListSizeReq,omitempty"`
	GetWhiteListReq               *Request_GetWhiteListRequest               `protobuf:"bytes,11,opt,name=getWhiteListReq" json:"getWhiteListReq,omitempty"`
	SgxGetExtendedEpidGroupIdReq  *Request_SGXGetExtendedEpidGroupIdRequest  `protobuf:"bytes,12,opt,name=sgxGetExtendedEpidGroupIdReq" json:"sgxGetExtendedEpidGroupIdReq,omitempty"`
	SgxSwitchExtendedEpidGroupReq *Request_SGXSwitchExtendedEpidGroupRequest `protobuf:"bytes,13,opt,name=sgxSwitchExtendedEpidGroupReq" json:"sgxSwitchExtendedEpidGroupReq,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}                                   `json:"-"`
	XXX_unrecognized              []byte                                     `json:"-"`
	XXX_sizecache                 int32                                      `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInitQuoteReq() *Request_InitQuoteRequest {
	if m != nil {
		return m.InitQuoteReq
	}
	return nil
}

func (m *Request) GetGetQuoteReq() *Request_GetQuoteRequest {
	if m != nil {
		return m.GetQuoteReq
	}
	return nil
}

func (m *Request) GetGetLicTokenReq() *Request_GetLaunchTokenRequest {
	if m != nil {
		return m.GetLicTokenReq
	}
	return nil
}

func (m *Request) GetReportErrReq() *Request_ReportAttestationErrorRequest {
	if m != nil {
		return m.ReportErrReq
	}
	return nil
}

func (m *Request) GetCreateSessionReq() *Request_CreateSessionRequest {
	if m != nil {
		return m.CreateSessionReq
	}
	return nil
}

func (m *Request) GetInvokeServiceReq() *Request_InvokeServiceRequest {
	if m != nil {
		return m.InvokeServiceReq
	}
	return nil
}

func (m *Request) GetExchangeReportReq() *Request_ExchangeReportRequest {
	if m != nil {
		return m.ExchangeReportReq
	}
	return nil
}

func (m *Request) GetCloseSessionReq() *Request_CloseSessionRequest {
	if m != nil {
		return m.CloseSessionReq
	}
	return nil
}

func (m *Request) GetGetPsCapReq() *Request_GetPsCapRequest {
	if m != nil {
		return m.GetPsCapReq
	}
	return nil
}

func (m *Request) GetGetWhiteListSizeReq() *Request_GetWhiteListSizeRequest {
	if m != nil {
		return m.GetWhiteListSizeReq
	}
	return nil
}

func (m *Request) GetGetWhiteListReq() *Request_GetWhiteListRequest {
	if m != nil {
		return m.GetWhiteListReq
	}
	return nil
}

func (m *Request) GetSgxGetExtendedEpidGroupIdReq() *Request_SGXGetExtendedEpidGroupIdRequest {
	if m != nil {
		return m.SgxGetExtendedEpidGroupIdReq
	}
	return nil
}

func (m *Request) GetSgxSwitchExtendedEpidGroupReq() *Request_SGXSwitchExtendedEpidGroupRequest {
	if m != nil {
		return m.SgxSwitchExtendedEpidGroupReq
	}
	return nil
}

type Request_InitQuoteRequest struct {
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_InitQuoteRequest) Reset()         { *m = Request_InitQuoteRequest{} }
func (m *Request_InitQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*Request_InitQuoteRequest) ProtoMessage()    {}
func (*Request_InitQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 0}
}
func (m *Request_InitQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_InitQuoteRequest.Unmarshal(m, b)
}
func (m *Request_InitQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_InitQuoteRequest.Marshal(b, m, deterministic)
}
func (dst *Request_InitQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_InitQuoteRequest.Merge(dst, src)
}
func (m *Request_InitQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_Request_InitQuoteRequest.Size(m)
}
func (m *Request_InitQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_InitQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_InitQuoteRequest proto.InternalMessageInfo

func (m *Request_InitQuoteRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_GetQuoteRequest struct {
	Report               []byte   `protobuf:"bytes,1,req,name=report" json:"report,omitempty"`
	QuoteType            *uint32  `protobuf:"varint,2,req,name=quote_type,json=quoteType" json:"quote_type,omitempty"`
	Spid                 []byte   `protobuf:"bytes,3,req,name=spid" json:"spid,omitempty"`
	Nonce                []byte   `protobuf:"bytes,4,opt,name=nonce" json:"nonce,omitempty"`
	SigRl                []byte   `protobuf:"bytes,5,opt,name=sig_rl,json=sigRl" json:"sig_rl,omitempty"`
	BufSize              *uint32  `protobuf:"varint,6,req,name=buf_size,json=bufSize" json:"buf_size,omitempty"`
	QeReport             *bool    `protobuf:"varint,7,opt,name=qe_report,json=qeReport" json:"qe_report,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_GetQuoteRequest) Reset()         { *m = Request_GetQuoteRequest{} }
func (m *Request_GetQuoteRequest) String() string { return proto.CompactTextString(m) }
func (*Request_GetQuoteRequest) ProtoMessage()    {}
func (*Request_GetQuoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 1}
}
func (m *Request_GetQuoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_GetQuoteRequest.Unmarshal(m, b)
}
func (m *Request_GetQuoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_GetQuoteRequest.Marshal(b, m, deterministic)
}
func (dst *Request_GetQuoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_GetQuoteRequest.Merge(dst, src)
}
func (m *Request_GetQuoteRequest) XXX_Size() int {
	return xxx_messageInfo_Request_GetQuoteRequest.Size(m)
}
func (m *Request_GetQuoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_GetQuoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_GetQuoteRequest proto.InternalMessageInfo

func (m *Request_GetQuoteRequest) GetReport() []byte {
	if m != nil {
		return m.Report
	}
	return nil
}

func (m *Request_GetQuoteRequest) GetQuoteType() uint32 {
	if m != nil && m.QuoteType != nil {
		return *m.QuoteType
	}
	return 0
}

func (m *Request_GetQuoteRequest) GetSpid() []byte {
	if m != nil {
		return m.Spid
	}
	return nil
}

func (m *Request_GetQuoteRequest) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *Request_GetQuoteRequest) GetSigRl() []byte {
	if m != nil {
		return m.SigRl
	}
	return nil
}

func (m *Request_GetQuoteRequest) GetBufSize() uint32 {
	if m != nil && m.BufSize != nil {
		return *m.BufSize
	}
	return 0
}

func (m *Request_GetQuoteRequest) GetQeReport() bool {
	if m != nil && m.QeReport != nil {
		return *m.QeReport
	}
	return false
}

func (m *Request_GetQuoteRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_GetLaunchTokenRequest struct {
	MrEnclave            []byte   `protobuf:"bytes,1,req,name=mr_enclave,json=mrEnclave" json:"mr_enclave,omitempty"`
	MrSigner             []byte   `protobuf:"bytes,2,req,name=mr_signer,json=mrSigner" json:"mr_signer,omitempty"`
	SeAttributes         []byte   `protobuf:"bytes,3,req,name=se_attributes,json=seAttributes" json:"se_attributes,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_GetLaunchTokenRequest) Reset()         { *m = Request_GetLaunchTokenRequest{} }
func (m *Request_GetLaunchTokenRequest) String() string { return proto.CompactTextString(m) }
func (*Request_GetLaunchTokenRequest) ProtoMessage()    {}
func (*Request_GetLaunchTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 2}
}
func (m *Request_GetLaunchTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_GetLaunchTokenRequest.Unmarshal(m, b)
}
func (m *Request_GetLaunchTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_GetLaunchTokenRequest.Marshal(b, m, deterministic)
}
func (dst *Request_GetLaunchTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_GetLaunchTokenRequest.Merge(dst, src)
}
func (m *Request_GetLaunchTokenRequest) XXX_Size() int {
	return xxx_messageInfo_Request_GetLaunchTokenRequest.Size(m)
}
func (m *Request_GetLaunchTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_GetLaunchTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_GetLaunchTokenRequest proto.InternalMessageInfo

func (m *Request_GetLaunchTokenRequest) GetMrEnclave() []byte {
	if m != nil {
		return m.MrEnclave
	}
	return nil
}

func (m *Request_GetLaunchTokenRequest) GetMrSigner() []byte {
	if m != nil {
		return m.MrSigner
	}
	return nil
}

func (m *Request_GetLaunchTokenRequest) GetSeAttributes() []byte {
	if m != nil {
		return m.SeAttributes
	}
	return nil
}

func (m *Request_GetLaunchTokenRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_ReportAttestationErrorRequest struct {
	PlatformInfo         []byte   `protobuf:"bytes,1,req,name=platform_info,json=platformInfo" json:"platform_info,omitempty"`
	AttestationErrorCode *uint32  `protobuf:"varint,2,req,name=attestation_error_code,json=attestationErrorCode" json:"attestation_error_code,omitempty"`
	UpdateInfoSize       *uint32  `protobuf:"varint,3,req,name=update_info_size,json=updateInfoSize" json:"update_info_size,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_ReportAttestationErrorRequest) Reset()         { *m = Request_ReportAttestationErrorRequest{} }
func (m *Request_ReportAttestationErrorRequest) String() string { return proto.CompactTextString(m) }
func (*Request_ReportAttestationErrorRequest) ProtoMessage()    {}
func (*Request_ReportAttestationErrorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 3}
}
func (m *Request_ReportAttestationErrorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_ReportAttestationErrorRequest.Unmarshal(m, b)
}
func (m *Request_ReportAttestationErrorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_ReportAttestationErrorRequest.Marshal(b, m, deterministic)
}
func (dst *Request_ReportAttestationErrorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_ReportAttestationErrorRequest.Merge(dst, src)
}
func (m *Request_ReportAttestationErrorRequest) XXX_Size() int {
	return xxx_messageInfo_Request_ReportAttestationErrorRequest.Size(m)
}
func (m *Request_ReportAttestationErrorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_ReportAttestationErrorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_ReportAttestationErrorRequest proto.InternalMessageInfo

func (m *Request_ReportAttestationErrorRequest) GetPlatformInfo() []byte {
	if m != nil {
		return m.PlatformInfo
	}
	return nil
}

func (m *Request_ReportAttestationErrorRequest) GetAttestationErrorCode() uint32 {
	if m != nil && m.AttestationErrorCode != nil {
		return *m.AttestationErrorCode
	}
	return 0
}

func (m *Request_ReportAttestationErrorRequest) GetUpdateInfoSize() uint32 {
	if m != nil && m.UpdateInfoSize != nil {
		return *m.UpdateInfoSize
	}
	return 0
}

func (m *Request_ReportAttestationErrorRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

// private API
type Request_CreateSessionRequest struct {
	DhMsg1Size           *uint32  `protobuf:"varint,1,req,name=dh_msg1_size,json=dhMsg1Size" json:"dh_msg1_size,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_CreateSessionRequest) Reset()         { *m = Request_CreateSessionRequest{} }
func (m *Request_CreateSessionRequest) String() string { return proto.CompactTextString(m) }
func (*Request_CreateSessionRequest) ProtoMessage()    {}
func (*Request_CreateSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 4}
}
func (m *Request_CreateSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_CreateSessionRequest.Unmarshal(m, b)
}
func (m *Request_CreateSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_CreateSessionRequest.Marshal(b, m, deterministic)
}
func (dst *Request_CreateSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_CreateSessionRequest.Merge(dst, src)
}
func (m *Request_CreateSessionRequest) XXX_Size() int {
	return xxx_messageInfo_Request_CreateSessionRequest.Size(m)
}
func (m *Request_CreateSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_CreateSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_CreateSessionRequest proto.InternalMessageInfo

func (m *Request_CreateSessionRequest) GetDhMsg1Size() uint32 {
	if m != nil && m.DhMsg1Size != nil {
		return *m.DhMsg1Size
	}
	return 0
}

func (m *Request_CreateSessionRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_InvokeServiceRequest struct {
	PseMessage           []byte   `protobuf:"bytes,1,req,name=pse_message,json=pseMessage" json:"pse_message,omitempty"`
	PseRespSize          *uint32  `protobuf:"varint,2,req,name=pse_resp_size,json=pseRespSize" json:"pse_resp_size,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_InvokeServiceRequest) Reset()         { *m = Request_InvokeServiceRequest{} }
func (m *Request_InvokeServiceRequest) String() string { return proto.CompactTextString(m) }
func (*Request_InvokeServiceRequest) ProtoMessage()    {}
func (*Request_InvokeServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 5}
}
func (m *Request_InvokeServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_InvokeServiceRequest.Unmarshal(m, b)
}
func (m *Request_InvokeServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_InvokeServiceRequest.Marshal(b, m, deterministic)
}
func (dst *Request_InvokeServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_InvokeServiceRequest.Merge(dst, src)
}
func (m *Request_InvokeServiceRequest) XXX_Size() int {
	return xxx_messageInfo_Request_InvokeServiceRequest.Size(m)
}
func (m *Request_InvokeServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_InvokeServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_InvokeServiceRequest proto.InternalMessageInfo

func (m *Request_InvokeServiceRequest) GetPseMessage() []byte {
	if m != nil {
		return m.PseMessage
	}
	return nil
}

func (m *Request_InvokeServiceRequest) GetPseRespSize() uint32 {
	if m != nil && m.PseRespSize != nil {
		return *m.PseRespSize
	}
	return 0
}

func (m *Request_InvokeServiceRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_ExchangeReportRequest struct {
	SessionId            *uint32  `protobuf:"varint,1,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	SeDhMsg2             []byte   `protobuf:"bytes,2,req,name=se_dh_msg2,json=seDhMsg2" json:"se_dh_msg2,omitempty"`
	SeDhMsg3Size         *uint32  `protobuf:"varint,3,req,name=se_dh_msg3_size,json=seDhMsg3Size" json:"se_dh_msg3_size,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_ExchangeReportRequest) Reset()         { *m = Request_ExchangeReportRequest{} }
func (m *Request_ExchangeReportRequest) String() string { return proto.CompactTextString(m) }
func (*Request_ExchangeReportRequest) ProtoMessage()    {}
func (*Request_ExchangeReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 6}
}
func (m *Request_ExchangeReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_ExchangeReportRequest.Unmarshal(m, b)
}
func (m *Request_ExchangeReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_ExchangeReportRequest.Marshal(b, m, deterministic)
}
func (dst *Request_ExchangeReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_ExchangeReportRequest.Merge(dst, src)
}
func (m *Request_ExchangeReportRequest) XXX_Size() int {
	return xxx_messageInfo_Request_ExchangeReportRequest.Size(m)
}
func (m *Request_ExchangeReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_ExchangeReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_ExchangeReportRequest proto.InternalMessageInfo

func (m *Request_ExchangeReportRequest) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *Request_ExchangeReportRequest) GetSeDhMsg2() []byte {
	if m != nil {
		return m.SeDhMsg2
	}
	return nil
}

func (m *Request_ExchangeReportRequest) GetSeDhMsg3Size() uint32 {
	if m != nil && m.SeDhMsg3Size != nil {
		return *m.SeDhMsg3Size
	}
	return 0
}

func (m *Request_ExchangeReportRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_CloseSessionRequest struct {
	SessionId            *uint32  `protobuf:"varint,1,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_CloseSessionRequest) Reset()         { *m = Request_CloseSessionRequest{} }
func (m *Request_CloseSessionRequest) String() string { return proto.CompactTextString(m) }
func (*Request_CloseSessionRequest) ProtoMessage()    {}
func (*Request_CloseSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 7}
}
func (m *Request_CloseSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_CloseSessionRequest.Unmarshal(m, b)
}
func (m *Request_CloseSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_CloseSessionRequest.Marshal(b, m, deterministic)
}
func (dst *Request_CloseSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_CloseSessionRequest.Merge(dst, src)
}
func (m *Request_CloseSessionRequest) XXX_Size() int {
	return xxx_messageInfo_Request_CloseSessionRequest.Size(m)
}
func (m *Request_CloseSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_CloseSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_CloseSessionRequest proto.InternalMessageInfo

func (m *Request_CloseSessionRequest) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *Request_CloseSessionRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_GetPsCapRequest struct {
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_GetPsCapRequest) Reset()         { *m = Request_GetPsCapRequest{} }
func (m *Request_GetPsCapRequest) String() string { return proto.CompactTextString(m) }
func (*Request_GetPsCapRequest) ProtoMessage()    {}
func (*Request_GetPsCapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 8}
}
func (m *Request_GetPsCapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_GetPsCapRequest.Unmarshal(m, b)
}
func (m *Request_GetPsCapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_GetPsCapRequest.Marshal(b, m, deterministic)
}
func (dst *Request_GetPsCapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_GetPsCapRequest.Merge(dst, src)
}
func (m *Request_GetPsCapRequest) XXX_Size() int {
	return xxx_messageInfo_Request_GetPsCapRequest.Size(m)
}
func (m *Request_GetPsCapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_GetPsCapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_GetPsCapRequest proto.InternalMessageInfo

func (m *Request_GetPsCapRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_GetWhiteListSizeRequest struct {
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_GetWhiteListSizeRequest) Reset()         { *m = Request_GetWhiteListSizeRequest{} }
func (m *Request_GetWhiteListSizeRequest) String() string { return proto.CompactTextString(m) }
func (*Request_GetWhiteListSizeRequest) ProtoMessage()    {}
func (*Request_GetWhiteListSizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 9}
}
func (m *Request_GetWhiteListSizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_GetWhiteListSizeRequest.Unmarshal(m, b)
}
func (m *Request_GetWhiteListSizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_GetWhiteListSizeRequest.Marshal(b, m, deterministic)
}
func (dst *Request_GetWhiteListSizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_GetWhiteListSizeRequest.Merge(dst, src)
}
func (m *Request_GetWhiteListSizeRequest) XXX_Size() int {
	return xxx_messageInfo_Request_GetWhiteListSizeRequest.Size(m)
}
func (m *Request_GetWhiteListSizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_GetWhiteListSizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_GetWhiteListSizeRequest proto.InternalMessageInfo

func (m *Request_GetWhiteListSizeRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_GetWhiteListRequest struct {
	WhiteListSize        *uint32  `protobuf:"varint,1,opt,name=white_list_size,json=whiteListSize" json:"white_list_size,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_GetWhiteListRequest) Reset()         { *m = Request_GetWhiteListRequest{} }
func (m *Request_GetWhiteListRequest) String() string { return proto.CompactTextString(m) }
func (*Request_GetWhiteListRequest) ProtoMessage()    {}
func (*Request_GetWhiteListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 10}
}
func (m *Request_GetWhiteListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_GetWhiteListRequest.Unmarshal(m, b)
}
func (m *Request_GetWhiteListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_GetWhiteListRequest.Marshal(b, m, deterministic)
}
func (dst *Request_GetWhiteListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_GetWhiteListRequest.Merge(dst, src)
}
func (m *Request_GetWhiteListRequest) XXX_Size() int {
	return xxx_messageInfo_Request_GetWhiteListRequest.Size(m)
}
func (m *Request_GetWhiteListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_GetWhiteListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_GetWhiteListRequest proto.InternalMessageInfo

func (m *Request_GetWhiteListRequest) GetWhiteListSize() uint32 {
	if m != nil && m.WhiteListSize != nil {
		return *m.WhiteListSize
	}
	return 0
}

func (m *Request_GetWhiteListRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_SGXGetExtendedEpidGroupIdRequest struct {
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_SGXGetExtendedEpidGroupIdRequest) Reset() {
	*m = Request_SGXGetExtendedEpidGroupIdRequest{}
}
func (m *Request_SGXGetExtendedEpidGroupIdRequest) String() string { return proto.CompactTextString(m) }
func (*Request_SGXGetExtendedEpidGroupIdRequest) ProtoMessage()    {}
func (*Request_SGXGetExtendedEpidGroupIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 11}
}
func (m *Request_SGXGetExtendedEpidGroupIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_SGXGetExtendedEpidGroupIdRequest.Unmarshal(m, b)
}
func (m *Request_SGXGetExtendedEpidGroupIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_SGXGetExtendedEpidGroupIdRequest.Marshal(b, m, deterministic)
}
func (dst *Request_SGXGetExtendedEpidGroupIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_SGXGetExtendedEpidGroupIdRequest.Merge(dst, src)
}
func (m *Request_SGXGetExtendedEpidGroupIdRequest) XXX_Size() int {
	return xxx_messageInfo_Request_SGXGetExtendedEpidGroupIdRequest.Size(m)
}
func (m *Request_SGXGetExtendedEpidGroupIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_SGXGetExtendedEpidGroupIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_SGXGetExtendedEpidGroupIdRequest proto.InternalMessageInfo

func (m *Request_SGXGetExtendedEpidGroupIdRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Request_SGXSwitchExtendedEpidGroupRequest struct {
	XGroupId             *uint32  `protobuf:"varint,1,opt,name=x_group_id,json=xGroupId" json:"x_group_id,omitempty"`
	Timeout              *uint32  `protobuf:"varint,9,opt,name=timeout" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request_SGXSwitchExtendedEpidGroupRequest) Reset() {
	*m = Request_SGXSwitchExtendedEpidGroupRequest{}
}
func (m *Request_SGXSwitchExtendedEpidGroupRequest) String() string { return proto.CompactTextString(m) }
func (*Request_SGXSwitchExtendedEpidGroupRequest) ProtoMessage()    {}
func (*Request_SGXSwitchExtendedEpidGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{0, 12}
}
func (m *Request_SGXSwitchExtendedEpidGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request_SGXSwitchExtendedEpidGroupRequest.Unmarshal(m, b)
}
func (m *Request_SGXSwitchExtendedEpidGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request_SGXSwitchExtendedEpidGroupRequest.Marshal(b, m, deterministic)
}
func (dst *Request_SGXSwitchExtendedEpidGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request_SGXSwitchExtendedEpidGroupRequest.Merge(dst, src)
}
func (m *Request_SGXSwitchExtendedEpidGroupRequest) XXX_Size() int {
	return xxx_messageInfo_Request_SGXSwitchExtendedEpidGroupRequest.Size(m)
}
func (m *Request_SGXSwitchExtendedEpidGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Request_SGXSwitchExtendedEpidGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_Request_SGXSwitchExtendedEpidGroupRequest proto.InternalMessageInfo

func (m *Request_SGXSwitchExtendedEpidGroupRequest) GetXGroupId() uint32 {
	if m != nil && m.XGroupId != nil {
		return *m.XGroupId
	}
	return 0
}

func (m *Request_SGXSwitchExtendedEpidGroupRequest) GetTimeout() uint32 {
	if m != nil && m.Timeout != nil {
		return *m.Timeout
	}
	return 0
}

type Response struct {
	InitQuoteRes                  *Response_InitQuoteResponse                  `protobuf:"bytes,1,opt,name=initQuoteRes" json:"initQuoteRes,omitempty"`
	GetQuoteRes                   *Response_GetQuoteResponse                   `protobuf:"bytes,2,opt,name=getQuoteRes" json:"getQuoteRes,omitempty"`
	GetLicTokenRes                *Response_GetLaunchTokenResponse             `protobuf:"bytes,3,opt,name=getLicTokenRes" json:"getLicTokenRes,omitempty"`
	ReportErrRes                  *Response_ReportAttestationErrorResponse     `protobuf:"bytes,4,opt,name=reportErrRes" json:"reportErrRes,omitempty"`
	CreateSessionRes              *Response_CreateSessionResponse              `protobuf:"bytes,5,opt,name=createSessionRes" json:"createSessionRes,omitempty"`
	InvokeServiceRes              *Response_InvokeServiceResponse              `protobuf:"bytes,6,opt,name=invokeServiceRes" json:"invokeServiceRes,omitempty"`
	ExchangeReportRes             *Response_ExchangeReportResponse             `protobuf:"bytes,7,opt,name=exchangeReportRes" json:"exchangeReportRes,omitempty"`
	CloseSessionRes               *Response_CloseSessionResponse               `protobuf:"bytes,8,opt,name=closeSessionRes" json:"closeSessionRes,omitempty"`
	GetPsCapRes                   *Response_GetPsCapResponse                   `protobuf:"bytes,9,opt,name=getPsCapRes" json:"getPsCapRes,omitempty"`
	GetWhiteListSizeRes           *Response_GetWhiteListSizeResponse           `protobuf:"bytes,10,opt,name=getWhiteListSizeRes" json:"getWhiteListSizeRes,omitempty"`
	GetWhiteListRes               *Response_GetWhiteListResponse               `protobuf:"bytes,11,opt,name=getWhiteListRes" json:"getWhiteListRes,omitempty"`
	SgxGetExtendedEpidGroupIdRes  *Response_SGXGetExtendedEpidGroupIdResponse  `protobuf:"bytes,12,opt,name=sgxGetExtendedEpidGroupIdRes" json:"sgxGetExtendedEpidGroupIdRes,omitempty"`
	SgxSwitchExtendedEpidGroupRes *Response_SGXSwitchExtendedEpidGroupResponse `protobuf:"bytes,13,opt,name=sgxSwitchExtendedEpidGroupRes" json:"sgxSwitchExtendedEpidGroupRes,omitempty"`
	XXX_NoUnkeyedLiteral          struct{}                                     `json:"-"`
	XXX_unrecognized              []byte                                       `json:"-"`
	XXX_sizecache                 int32                                        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetInitQuoteRes() *Response_InitQuoteResponse {
	if m != nil {
		return m.InitQuoteRes
	}
	return nil
}

func (m *Response) GetGetQuoteRes() *Response_GetQuoteResponse {
	if m != nil {
		return m.GetQuoteRes
	}
	return nil
}

func (m *Response) GetGetLicTokenRes() *Response_GetLaunchTokenResponse {
	if m != nil {
		return m.GetLicTokenRes
	}
	return nil
}

func (m *Response) GetReportErrRes() *Response_ReportAttestationErrorResponse {
	if m != nil {
		return m.ReportErrRes
	}
	return nil
}

func (m *Response) GetCreateSessionRes() *Response_CreateSessionResponse {
	if m != nil {
		return m.CreateSessionRes
	}
	return nil
}

func (m *Response) GetInvokeServiceRes() *Response_InvokeServiceResponse {
	if m != nil {
		return m.InvokeServiceRes
	}
	return nil
}

func (m *Response) GetExchangeReportRes() *Response_ExchangeReportResponse {
	if m != nil {
		return m.ExchangeReportRes
	}
	return nil
}

func (m *Response) GetCloseSessionRes() *Response_CloseSessionResponse {
	if m != nil {
		return m.CloseSessionRes
	}
	return nil
}

func (m *Response) GetGetPsCapRes() *Response_GetPsCapResponse {
	if m != nil {
		return m.GetPsCapRes
	}
	return nil
}

func (m *Response) GetGetWhiteListSizeRes() *Response_GetWhiteListSizeResponse {
	if m != nil {
		return m.GetWhiteListSizeRes
	}
	return nil
}

func (m *Response) GetGetWhiteListRes() *Response_GetWhiteListResponse {
	if m != nil {
		return m.GetWhiteListRes
	}
	return nil
}

func (m *Response) GetSgxGetExtendedEpidGroupIdRes() *Response_SGXGetExtendedEpidGroupIdResponse {
	if m != nil {
		return m.SgxGetExtendedEpidGroupIdRes
	}
	return nil
}

func (m *Response) GetSgxSwitchExtendedEpidGroupRes() *Response_SGXSwitchExtendedEpidGroupResponse {
	if m != nil {
		return m.SgxSwitchExtendedEpidGroupRes
	}
	return nil
}

type Response_InitQuoteResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	TargetInfo           []byte   `protobuf:"bytes,2,opt,name=targetInfo" json:"targetInfo,omitempty"`
	Gid                  []byte   `protobuf:"bytes,3,opt,name=gid" json:"gid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_InitQuoteResponse) Reset()         { *m = Response_InitQuoteResponse{} }
func (m *Response_InitQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*Response_InitQuoteResponse) ProtoMessage()    {}
func (*Response_InitQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 0}
}
func (m *Response_InitQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_InitQuoteResponse.Unmarshal(m, b)
}
func (m *Response_InitQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_InitQuoteResponse.Marshal(b, m, deterministic)
}
func (dst *Response_InitQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_InitQuoteResponse.Merge(dst, src)
}
func (m *Response_InitQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_Response_InitQuoteResponse.Size(m)
}
func (m *Response_InitQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_InitQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_InitQuoteResponse proto.InternalMessageInfo

const Default_Response_InitQuoteResponse_ErrorCode uint32 = 1

func (m *Response_InitQuoteResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_InitQuoteResponse_ErrorCode
}

func (m *Response_InitQuoteResponse) GetTargetInfo() []byte {
	if m != nil {
		return m.TargetInfo
	}
	return nil
}

func (m *Response_InitQuoteResponse) GetGid() []byte {
	if m != nil {
		return m.Gid
	}
	return nil
}

type Response_GetQuoteResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	Quote                []byte   `protobuf:"bytes,2,opt,name=quote" json:"quote,omitempty"`
	QeReport             []byte   `protobuf:"bytes,3,opt,name=qe_report,json=qeReport" json:"qe_report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_GetQuoteResponse) Reset()         { *m = Response_GetQuoteResponse{} }
func (m *Response_GetQuoteResponse) String() string { return proto.CompactTextString(m) }
func (*Response_GetQuoteResponse) ProtoMessage()    {}
func (*Response_GetQuoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 1}
}
func (m *Response_GetQuoteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_GetQuoteResponse.Unmarshal(m, b)
}
func (m *Response_GetQuoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_GetQuoteResponse.Marshal(b, m, deterministic)
}
func (dst *Response_GetQuoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_GetQuoteResponse.Merge(dst, src)
}
func (m *Response_GetQuoteResponse) XXX_Size() int {
	return xxx_messageInfo_Response_GetQuoteResponse.Size(m)
}
func (m *Response_GetQuoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_GetQuoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_GetQuoteResponse proto.InternalMessageInfo

const Default_Response_GetQuoteResponse_ErrorCode uint32 = 1

func (m *Response_GetQuoteResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_GetQuoteResponse_ErrorCode
}

func (m *Response_GetQuoteResponse) GetQuote() []byte {
	if m != nil {
		return m.Quote
	}
	return nil
}

func (m *Response_GetQuoteResponse) GetQeReport() []byte {
	if m != nil {
		return m.QeReport
	}
	return nil
}

type Response_GetLaunchTokenResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	Token                []byte   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_GetLaunchTokenResponse) Reset()         { *m = Response_GetLaunchTokenResponse{} }
func (m *Response_GetLaunchTokenResponse) String() string { return proto.CompactTextString(m) }
func (*Response_GetLaunchTokenResponse) ProtoMessage()    {}
func (*Response_GetLaunchTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 2}
}
func (m *Response_GetLaunchTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_GetLaunchTokenResponse.Unmarshal(m, b)
}
func (m *Response_GetLaunchTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_GetLaunchTokenResponse.Marshal(b, m, deterministic)
}
func (dst *Response_GetLaunchTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_GetLaunchTokenResponse.Merge(dst, src)
}
func (m *Response_GetLaunchTokenResponse) XXX_Size() int {
	return xxx_messageInfo_Response_GetLaunchTokenResponse.Size(m)
}
func (m *Response_GetLaunchTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_GetLaunchTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_GetLaunchTokenResponse proto.InternalMessageInfo

const Default_Response_GetLaunchTokenResponse_ErrorCode uint32 = 1

func (m *Response_GetLaunchTokenResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_GetLaunchTokenResponse_ErrorCode
}

func (m *Response_GetLaunchTokenResponse) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

type Response_ReportAttestationErrorResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	PlatformUpdateInfo   []byte   `protobuf:"bytes,2,opt,name=platform_update_info,json=platformUpdateInfo" json:"platform_update_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_ReportAttestationErrorResponse) Reset() {
	*m = Response_ReportAttestationErrorResponse{}
}
func (m *Response_ReportAttestationErrorResponse) String() string { return proto.CompactTextString(m) }
func (*Response_ReportAttestationErrorResponse) ProtoMessage()    {}
func (*Response_ReportAttestationErrorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 3}
}
func (m *Response_ReportAttestationErrorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_ReportAttestationErrorResponse.Unmarshal(m, b)
}
func (m *Response_ReportAttestationErrorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_ReportAttestationErrorResponse.Marshal(b, m, deterministic)
}
func (dst *Response_ReportAttestationErrorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_ReportAttestationErrorResponse.Merge(dst, src)
}
func (m *Response_ReportAttestationErrorResponse) XXX_Size() int {
	return xxx_messageInfo_Response_ReportAttestationErrorResponse.Size(m)
}
func (m *Response_ReportAttestationErrorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_ReportAttestationErrorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_ReportAttestationErrorResponse proto.InternalMessageInfo

const Default_Response_ReportAttestationErrorResponse_ErrorCode uint32 = 1

func (m *Response_ReportAttestationErrorResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_ReportAttestationErrorResponse_ErrorCode
}

func (m *Response_ReportAttestationErrorResponse) GetPlatformUpdateInfo() []byte {
	if m != nil {
		return m.PlatformUpdateInfo
	}
	return nil
}

// private API
type Response_CreateSessionResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	SessionId            *uint32  `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`
	SeDhMsg1             []byte   `protobuf:"bytes,3,opt,name=se_dh_msg1,json=seDhMsg1" json:"se_dh_msg1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_CreateSessionResponse) Reset()         { *m = Response_CreateSessionResponse{} }
func (m *Response_CreateSessionResponse) String() string { return proto.CompactTextString(m) }
func (*Response_CreateSessionResponse) ProtoMessage()    {}
func (*Response_CreateSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 4}
}
func (m *Response_CreateSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_CreateSessionResponse.Unmarshal(m, b)
}
func (m *Response_CreateSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_CreateSessionResponse.Marshal(b, m, deterministic)
}
func (dst *Response_CreateSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_CreateSessionResponse.Merge(dst, src)
}
func (m *Response_CreateSessionResponse) XXX_Size() int {
	return xxx_messageInfo_Response_CreateSessionResponse.Size(m)
}
func (m *Response_CreateSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_CreateSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_CreateSessionResponse proto.InternalMessageInfo

const Default_Response_CreateSessionResponse_ErrorCode uint32 = 1

func (m *Response_CreateSessionResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_CreateSessionResponse_ErrorCode
}

func (m *Response_CreateSessionResponse) GetSessionId() uint32 {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return 0
}

func (m *Response_CreateSessionResponse) GetSeDhMsg1() []byte {
	if m != nil {
		return m.SeDhMsg1
	}
	return nil
}

type Response_InvokeServiceResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	PseMessage           []byte   `protobuf:"bytes,2,opt,name=pse_message,json=pseMessage" json:"pse_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_InvokeServiceResponse) Reset()         { *m = Response_InvokeServiceResponse{} }
func (m *Response_InvokeServiceResponse) String() string { return proto.CompactTextString(m) }
func (*Response_InvokeServiceResponse) ProtoMessage()    {}
func (*Response_InvokeServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 5}
}
func (m *Response_InvokeServiceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_InvokeServiceResponse.Unmarshal(m, b)
}
func (m *Response_InvokeServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_InvokeServiceResponse.Marshal(b, m, deterministic)
}
func (dst *Response_InvokeServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_InvokeServiceResponse.Merge(dst, src)
}
func (m *Response_InvokeServiceResponse) XXX_Size() int {
	return xxx_messageInfo_Response_InvokeServiceResponse.Size(m)
}
func (m *Response_InvokeServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_InvokeServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_InvokeServiceResponse proto.InternalMessageInfo

const Default_Response_InvokeServiceResponse_ErrorCode uint32 = 1

func (m *Response_InvokeServiceResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_InvokeServiceResponse_ErrorCode
}

func (m *Response_InvokeServiceResponse) GetPseMessage() []byte {
	if m != nil {
		return m.PseMessage
	}
	return nil
}

type Response_ExchangeReportResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	SeDhMsg3             []byte   `protobuf:"bytes,2,opt,name=se_dh_msg3,json=seDhMsg3" json:"se_dh_msg3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_ExchangeReportResponse) Reset()         { *m = Response_ExchangeReportResponse{} }
func (m *Response_ExchangeReportResponse) String() string { return proto.CompactTextString(m) }
func (*Response_ExchangeReportResponse) ProtoMessage()    {}
func (*Response_ExchangeReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 6}
}
func (m *Response_ExchangeReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_ExchangeReportResponse.Unmarshal(m, b)
}
func (m *Response_ExchangeReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_ExchangeReportResponse.Marshal(b, m, deterministic)
}
func (dst *Response_ExchangeReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_ExchangeReportResponse.Merge(dst, src)
}
func (m *Response_ExchangeReportResponse) XXX_Size() int {
	return xxx_messageInfo_Response_ExchangeReportResponse.Size(m)
}
func (m *Response_ExchangeReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_ExchangeReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_ExchangeReportResponse proto.InternalMessageInfo

const Default_Response_ExchangeReportResponse_ErrorCode uint32 = 1

func (m *Response_ExchangeReportResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_ExchangeReportResponse_ErrorCode
}

func (m *Response_ExchangeReportResponse) GetSeDhMsg3() []byte {
	if m != nil {
		return m.SeDhMsg3
	}
	return nil
}

type Response_CloseSessionResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_CloseSessionResponse) Reset()         { *m = Response_CloseSessionResponse{} }
func (m *Response_CloseSessionResponse) String() string { return proto.CompactTextString(m) }
func (*Response_CloseSessionResponse) ProtoMessage()    {}
func (*Response_CloseSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 7}
}
func (m *Response_CloseSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_CloseSessionResponse.Unmarshal(m, b)
}
func (m *Response_CloseSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_CloseSessionResponse.Marshal(b, m, deterministic)
}
func (dst *Response_CloseSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_CloseSessionResponse.Merge(dst, src)
}
func (m *Response_CloseSessionResponse) XXX_Size() int {
	return xxx_messageInfo_Response_CloseSessionResponse.Size(m)
}
func (m *Response_CloseSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_CloseSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_CloseSessionResponse proto.InternalMessageInfo

const Default_Response_CloseSessionResponse_ErrorCode uint32 = 1

func (m *Response_CloseSessionResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_CloseSessionResponse_ErrorCode
}

type Response_GetPsCapResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	PsCap                *uint64  `protobuf:"varint,2,opt,name=ps_cap,json=psCap" json:"ps_cap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_GetPsCapResponse) Reset()         { *m = Response_GetPsCapResponse{} }
func (m *Response_GetPsCapResponse) String() string { return proto.CompactTextString(m) }
func (*Response_GetPsCapResponse) ProtoMessage()    {}
func (*Response_GetPsCapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 8}
}
func (m *Response_GetPsCapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_GetPsCapResponse.Unmarshal(m, b)
}
func (m *Response_GetPsCapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_GetPsCapResponse.Marshal(b, m, deterministic)
}
func (dst *Response_GetPsCapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_GetPsCapResponse.Merge(dst, src)
}
func (m *Response_GetPsCapResponse) XXX_Size() int {
	return xxx_messageInfo_Response_GetPsCapResponse.Size(m)
}
func (m *Response_GetPsCapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_GetPsCapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_GetPsCapResponse proto.InternalMessageInfo

const Default_Response_GetPsCapResponse_ErrorCode uint32 = 1

func (m *Response_GetPsCapResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_GetPsCapResponse_ErrorCode
}

func (m *Response_GetPsCapResponse) GetPsCap() uint64 {
	if m != nil && m.PsCap != nil {
		return *m.PsCap
	}
	return 0
}

type Response_GetWhiteListSizeResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	WhiteListSize        *uint32  `protobuf:"varint,2,opt,name=white_list_size,json=whiteListSize" json:"white_list_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_GetWhiteListSizeResponse) Reset()         { *m = Response_GetWhiteListSizeResponse{} }
func (m *Response_GetWhiteListSizeResponse) String() string { return proto.CompactTextString(m) }
func (*Response_GetWhiteListSizeResponse) ProtoMessage()    {}
func (*Response_GetWhiteListSizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 9}
}
func (m *Response_GetWhiteListSizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_GetWhiteListSizeResponse.Unmarshal(m, b)
}
func (m *Response_GetWhiteListSizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_GetWhiteListSizeResponse.Marshal(b, m, deterministic)
}
func (dst *Response_GetWhiteListSizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_GetWhiteListSizeResponse.Merge(dst, src)
}
func (m *Response_GetWhiteListSizeResponse) XXX_Size() int {
	return xxx_messageInfo_Response_GetWhiteListSizeResponse.Size(m)
}
func (m *Response_GetWhiteListSizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_GetWhiteListSizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_GetWhiteListSizeResponse proto.InternalMessageInfo

const Default_Response_GetWhiteListSizeResponse_ErrorCode uint32 = 1

func (m *Response_GetWhiteListSizeResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_GetWhiteListSizeResponse_ErrorCode
}

func (m *Response_GetWhiteListSizeResponse) GetWhiteListSize() uint32 {
	if m != nil && m.WhiteListSize != nil {
		return *m.WhiteListSize
	}
	return 0
}

type Response_GetWhiteListResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	WhiteList            []byte   `protobuf:"bytes,2,opt,name=white_list,json=whiteList" json:"white_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_GetWhiteListResponse) Reset()         { *m = Response_GetWhiteListResponse{} }
func (m *Response_GetWhiteListResponse) String() string { return proto.CompactTextString(m) }
func (*Response_GetWhiteListResponse) ProtoMessage()    {}
func (*Response_GetWhiteListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 10}
}
func (m *Response_GetWhiteListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_GetWhiteListResponse.Unmarshal(m, b)
}
func (m *Response_GetWhiteListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_GetWhiteListResponse.Marshal(b, m, deterministic)
}
func (dst *Response_GetWhiteListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_GetWhiteListResponse.Merge(dst, src)
}
func (m *Response_GetWhiteListResponse) XXX_Size() int {
	return xxx_messageInfo_Response_GetWhiteListResponse.Size(m)
}
func (m *Response_GetWhiteListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_GetWhiteListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_GetWhiteListResponse proto.InternalMessageInfo

const Default_Response_GetWhiteListResponse_ErrorCode uint32 = 1

func (m *Response_GetWhiteListResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_GetWhiteListResponse_ErrorCode
}

func (m *Response_GetWhiteListResponse) GetWhiteList() []byte {
	if m != nil {
		return m.WhiteList
	}
	return nil
}

type Response_SGXGetExtendedEpidGroupIdResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	XGroupId             *uint32  `protobuf:"varint,2,opt,name=x_group_id,json=xGroupId" json:"x_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_SGXGetExtendedEpidGroupIdResponse) Reset() {
	*m = Response_SGXGetExtendedEpidGroupIdResponse{}
}
func (m *Response_SGXGetExtendedEpidGroupIdResponse) String() string {
	return proto.CompactTextString(m)
}
func (*Response_SGXGetExtendedEpidGroupIdResponse) ProtoMessage() {}
func (*Response_SGXGetExtendedEpidGroupIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 11}
}
func (m *Response_SGXGetExtendedEpidGroupIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_SGXGetExtendedEpidGroupIdResponse.Unmarshal(m, b)
}
func (m *Response_SGXGetExtendedEpidGroupIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_SGXGetExtendedEpidGroupIdResponse.Marshal(b, m, deterministic)
}
func (dst *Response_SGXGetExtendedEpidGroupIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_SGXGetExtendedEpidGroupIdResponse.Merge(dst, src)
}
func (m *Response_SGXGetExtendedEpidGroupIdResponse) XXX_Size() int {
	return xxx_messageInfo_Response_SGXGetExtendedEpidGroupIdResponse.Size(m)
}
func (m *Response_SGXGetExtendedEpidGroupIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_SGXGetExtendedEpidGroupIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_SGXGetExtendedEpidGroupIdResponse proto.InternalMessageInfo

const Default_Response_SGXGetExtendedEpidGroupIdResponse_ErrorCode uint32 = 1

func (m *Response_SGXGetExtendedEpidGroupIdResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_SGXGetExtendedEpidGroupIdResponse_ErrorCode
}

func (m *Response_SGXGetExtendedEpidGroupIdResponse) GetXGroupId() uint32 {
	if m != nil && m.XGroupId != nil {
		return *m.XGroupId
	}
	return 0
}

type Response_SGXSwitchExtendedEpidGroupResponse struct {
	ErrorCode            *uint32  `protobuf:"varint,1,req,name=errorCode,def=1" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response_SGXSwitchExtendedEpidGroupResponse) Reset() {
	*m = Response_SGXSwitchExtendedEpidGroupResponse{}
}
func (m *Response_SGXSwitchExtendedEpidGroupResponse) String() string {
	return proto.CompactTextString(m)
}
func (*Response_SGXSwitchExtendedEpidGroupResponse) ProtoMessage() {}
func (*Response_SGXSwitchExtendedEpidGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_aesm_proto_5fdd0f086b94d673, []int{1, 12}
}
func (m *Response_SGXSwitchExtendedEpidGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response_SGXSwitchExtendedEpidGroupResponse.Unmarshal(m, b)
}
func (m *Response_SGXSwitchExtendedEpidGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response_SGXSwitchExtendedEpidGroupResponse.Marshal(b, m, deterministic)
}
func (dst *Response_SGXSwitchExtendedEpidGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response_SGXSwitchExtendedEpidGroupResponse.Merge(dst, src)
}
func (m *Response_SGXSwitchExtendedEpidGroupResponse) XXX_Size() int {
	return xxx_messageInfo_Response_SGXSwitchExtendedEpidGroupResponse.Size(m)
}
func (m *Response_SGXSwitchExtendedEpidGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_Response_SGXSwitchExtendedEpidGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_Response_SGXSwitchExtendedEpidGroupResponse proto.InternalMessageInfo

const Default_Response_SGXSwitchExtendedEpidGroupResponse_ErrorCode uint32 = 1

func (m *Response_SGXSwitchExtendedEpidGroupResponse) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_Response_SGXSwitchExtendedEpidGroupResponse_ErrorCode
}

func init() {
	proto.RegisterType((*Request)(nil), "aesm.Request")
	proto.RegisterType((*Request_InitQuoteRequest)(nil), "aesm.Request.InitQuoteRequest")
	proto.RegisterType((*Request_GetQuoteRequest)(nil), "aesm.Request.GetQuoteRequest")
	proto.RegisterType((*Request_GetLaunchTokenRequest)(nil), "aesm.Request.GetLaunchTokenRequest")
	proto.RegisterType((*Request_ReportAttestationErrorRequest)(nil), "aesm.Request.ReportAttestationErrorRequest")
	proto.RegisterType((*Request_CreateSessionRequest)(nil), "aesm.Request.CreateSessionRequest")
	proto.RegisterType((*Request_InvokeServiceRequest)(nil), "aesm.Request.InvokeServiceRequest")
	proto.RegisterType((*Request_ExchangeReportRequest)(nil), "aesm.Request.ExchangeReportRequest")
	proto.RegisterType((*Request_CloseSessionRequest)(nil), "aesm.Request.CloseSessionRequest")
	proto.RegisterType((*Request_GetPsCapRequest)(nil), "aesm.Request.GetPsCapRequest")
	proto.RegisterType((*Request_GetWhiteListSizeRequest)(nil), "aesm.Request.GetWhiteListSizeRequest")
	proto.RegisterType((*Request_GetWhiteListRequest)(nil), "aesm.Request.GetWhiteListRequest")
	proto.RegisterType((*Request_SGXGetExtendedEpidGroupIdRequest)(nil), "aesm.Request.SGXGetExtendedEpidGroupIdRequest")
	proto.RegisterType((*Request_SGXSwitchExtendedEpidGroupRequest)(nil), "aesm.Request.SGXSwitchExtendedEpidGroupRequest")
	proto.RegisterType((*Response)(nil), "aesm.Response")
	proto.RegisterType((*Response_InitQuoteResponse)(nil), "aesm.Response.InitQuoteResponse")
	proto.RegisterType((*Response_GetQuoteResponse)(nil), "aesm.Response.GetQuoteResponse")
	proto.RegisterType((*Response_GetLaunchTokenResponse)(nil), "aesm.Response.GetLaunchTokenResponse")
	proto.RegisterType((*Response_ReportAttestationErrorResponse)(nil), "aesm.Response.ReportAttestationErrorResponse")
	proto.RegisterType((*Response_CreateSessionResponse)(nil), "aesm.Response.CreateSessionResponse")
	proto.RegisterType((*Response_InvokeServiceResponse)(nil), "aesm.Response.InvokeServiceResponse")
	proto.RegisterType((*Response_ExchangeReportResponse)(nil), "aesm.Response.ExchangeReportResponse")
	proto.RegisterType((*Response_CloseSessionResponse)(nil), "aesm.Response.CloseSessionResponse")
	proto.RegisterType((*Response_GetPsCapResponse)(nil), "aesm.Response.GetPsCapResponse")
	proto.RegisterType((*Response_GetWhiteListSizeResponse)(nil), "aesm.Response.GetWhiteListSizeResponse")
	proto.RegisterType((*Response_GetWhiteListResponse)(nil), "aesm.Response.GetWhiteListResponse")
	proto.RegisterType((*Response_SGXGetExtendedEpidGroupIdResponse)(nil), "aesm.Response.SGXGetExtendedEpidGroupIdResponse")
	proto.RegisterType((*Response_SGXSwitchExtendedEpidGroupResponse)(nil), "aesm.Response.SGXSwitchExtendedEpidGroupResponse")
}

func init() { proto.RegisterFile("aesm_proto.proto", fileDescriptor_aesm_proto_5fdd0f086b94d673) }

var fileDescriptor_aesm_proto_5fdd0f086b94d673 = []byte{
	// 1363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x96, 0xdf, 0x6e, 0xdb, 0x36,
	0x14, 0xc6, 0x61, 0xe7, 0x9f, 0x7d, 0x22, 0x37, 0x2e, 0x63, 0x67, 0x9e, 0xd6, 0xb4, 0x6e, 0xd2,
	0x6c, 0x01, 0xba, 0x65, 0x75, 0x32, 0x60, 0xc0, 0x30, 0x60, 0xc8, 0x52, 0x23, 0xc8, 0x9a, 0xb4,
	0x8d, 0xdc, 0x2d, 0x2b, 0x76, 0x21, 0x28, 0x12, 0x2d, 0x0b, 0xb5, 0x25, 0x45, 0xa4, 0x12, 0xb7,
	0x2f, 0xb0, 0xfb, 0x01, 0x7b, 0x88, 0xbd, 0xc4, 0x5e, 0x64, 0x2f, 0x33, 0x90, 0xa2, 0x6c, 0x89,
	0x92, 0xa5, 0xdc, 0x04, 0xd1, 0xf1, 0x39, 0xbf, 0xc3, 0x43, 0x91, 0x9f, 0x3e, 0x68, 0x1a, 0x98,
	0x4c, 0x74, 0x3f, 0xf0, 0xa8, 0x77, 0xc0, 0xff, 0xa2, 0x65, 0x16, 0xd9, 0xf9, 0x67, 0x13, 0xd6,
	0x34, 0x7c, 0x13, 0x62, 0x42, 0xd1, 0xcf, 0xa0, 0x38, 0xae, 0x43, 0x2f, 0x43, 0x8f, 0x62, 0x0d,
	0xdf, 0x74, 0x2a, 0xdd, 0xca, 0xfe, 0xfa, 0xe1, 0xe3, 0x03, 0x96, 0x78, 0x20, 0x92, 0x0e, 0xce,
	0x12, 0x19, 0x2c, 0xa0, 0xa5, 0x6a, 0xd0, 0x4f, 0xb0, 0x6e, 0xe3, 0x39, 0xa2, 0xca, 0x11, 0xdb,
	0x69, 0xc4, 0x29, 0x4e, 0x13, 0x92, 0x15, 0xe8, 0x15, 0x3c, 0xb0, 0x31, 0x3d, 0x77, 0xcc, 0x77,
	0xde, 0x07, 0xec, 0x32, 0xc6, 0x12, 0x67, 0xec, 0x66, 0x18, 0xe7, 0x46, 0xe8, 0x9a, 0xa3, 0x38,
	0x8d, 0x93, 0xa4, 0x52, 0xf4, 0x06, 0x94, 0x00, 0xfb, 0x5e, 0x40, 0xfb, 0x41, 0xc0, 0x50, 0xcb,
	0x1c, 0xf5, 0x3c, 0x8d, 0xd2, 0x78, 0xc6, 0x31, 0xa5, 0x98, 0x50, 0x83, 0x3a, 0x9e, 0xdb, 0x0f,
	0x02, 0x2f, 0x98, 0x8d, 0x97, 0x04, 0xa0, 0xd7, 0xd0, 0x34, 0x03, 0x6c, 0x50, 0x3c, 0xc0, 0x84,
	0x38, 0x1e, 0x5f, 0xdf, 0x0a, 0x87, 0xee, 0xa4, 0xa1, 0x27, 0x52, 0x16, 0x67, 0x65, 0x6a, 0x19,
	0xcf, 0x71, 0x6f, 0xbd, 0x0f, 0x78, 0x80, 0x83, 0x5b, 0xc7, 0xe4, 0x7b, 0xb6, 0x9a, 0xc7, 0x3b,
	0x93, 0xb2, 0x22, 0x9e, 0x5c, 0x8b, 0x2e, 0xe1, 0x21, 0x9e, 0x9a, 0x23, 0xc3, 0xb5, 0x71, 0x34,
	0x16, 0x03, 0xae, 0xe5, 0x6d, 0x60, 0x5f, 0x4e, 0xe3, 0xc4, 0x6c, 0x35, 0x7a, 0x05, 0x1b, 0xe6,
	0xd8, 0x23, 0xc9, 0x89, 0x6b, 0x1c, 0xf8, 0x54, 0x9a, 0x38, 0x9d, 0xc4, 0x71, 0x72, 0xa5, 0x38,
	0x1e, 0x6f, 0xc9, 0x89, 0xe1, 0x33, 0x50, 0x7d, 0xc1, 0xf1, 0x88, 0x13, 0x66, 0xc7, 0x23, 0x0e,
	0xa0, 0x2b, 0xd8, 0xb4, 0x31, 0xbd, 0x1a, 0x39, 0x14, 0x9f, 0x3b, 0x84, 0x0e, 0x9c, 0x4f, 0x7c,
	0xcf, 0x80, 0x83, 0xf6, 0x32, 0x20, 0x39, 0x91, 0x03, 0xf3, 0x08, 0x6c, 0xcc, 0x64, 0x98, 0x41,
	0xd7, 0xf3, 0xc6, 0x3c, 0x4d, 0x27, 0x45, 0x63, 0x4a, 0x95, 0x28, 0x80, 0x47, 0xc4, 0x9e, 0x9e,
	0x62, 0xda, 0x9f, 0x52, 0xec, 0x5a, 0xd8, 0xea, 0xfb, 0x8e, 0x75, 0x1a, 0x78, 0xa1, 0x7f, 0x66,
	0x31, 0xb2, 0xc2, 0xc9, 0x07, 0x69, 0xf2, 0xe0, 0xf4, 0xf7, 0x85, 0x15, 0xbc, 0x4d, 0x21, 0x13,
	0x85, 0xb0, 0x4d, 0xec, 0xe9, 0xe0, 0xce, 0xa1, 0xe6, 0x28, 0x93, 0xc2, 0x9a, 0x36, 0x78, 0xd3,
	0x6f, 0x33, 0x4d, 0x17, 0x97, 0xf0, 0xae, 0xc5, 0x54, 0xf5, 0x6b, 0x68, 0xca, 0x92, 0x80, 0x3a,
	0xb0, 0x46, 0x9d, 0x09, 0xf6, 0x42, 0xca, 0xdf, 0x70, 0x43, 0x8b, 0x1f, 0xd5, 0xff, 0x2a, 0xb0,
	0x21, 0x5d, 0x7f, 0xb4, 0x05, 0xab, 0xd1, 0x1d, 0xeb, 0x54, 0xba, 0xd5, 0x7d, 0x45, 0x13, 0x4f,
	0x68, 0x1b, 0xe0, 0x86, 0xe5, 0xe9, 0xf4, 0xa3, 0x8f, 0x3b, 0xd5, 0x6e, 0x75, 0xbf, 0xa1, 0xd5,
	0x79, 0xe4, 0xdd, 0x47, 0x1f, 0x23, 0x04, 0xcb, 0xc4, 0x77, 0xac, 0xce, 0x12, 0x2f, 0xe2, 0xff,
	0xa3, 0x16, 0xac, 0xb8, 0x9e, 0x6b, 0x62, 0x7e, 0xd1, 0x15, 0x2d, 0x7a, 0x40, 0x6d, 0x58, 0x25,
	0x8e, 0xad, 0x07, 0x63, 0x7e, 0x55, 0x15, 0x6d, 0x85, 0x38, 0xb6, 0x36, 0x46, 0x9f, 0x43, 0xed,
	0x3a, 0x1c, 0xea, 0xc4, 0xf9, 0x84, 0x3b, 0xab, 0x9c, 0xbe, 0x76, 0x1d, 0x0e, 0xd9, 0x79, 0x40,
	0x5f, 0x40, 0xfd, 0x06, 0xeb, 0x62, 0x55, 0xec, 0xfa, 0xd4, 0xb4, 0xda, 0x8d, 0xb8, 0x13, 0x05,
	0xd3, 0xfd, 0x55, 0x81, 0x76, 0xae, 0x30, 0xb1, 0x59, 0x26, 0x81, 0x8e, 0x5d, 0x73, 0x6c, 0xdc,
	0x62, 0x31, 0x67, 0x7d, 0x12, 0xf4, 0xa3, 0x00, 0xeb, 0x37, 0x09, 0x74, 0xe2, 0xd8, 0x2e, 0x0e,
	0xf8, 0xa4, 0x8a, 0x56, 0x9b, 0x04, 0x03, 0xfe, 0x8c, 0x76, 0xa1, 0x41, 0xb0, 0x6e, 0x50, 0x1a,
	0x38, 0xd7, 0x21, 0xc5, 0x44, 0x4c, 0xac, 0x10, 0x7c, 0x3c, 0x8b, 0x15, 0x2c, 0xea, 0xdf, 0x0a,
	0x6c, 0x17, 0x4a, 0x1c, 0x6b, 0xe0, 0x8f, 0x0d, 0x3a, 0xf4, 0x82, 0x89, 0xee, 0xb8, 0x43, 0x4f,
	0xac, 0x4f, 0x89, 0x83, 0x67, 0xee, 0xd0, 0x43, 0xdf, 0xc1, 0x96, 0x31, 0xaf, 0xd7, 0x31, 0x03,
	0xe8, 0xa6, 0x67, 0xc5, 0x6f, 0xa6, 0x65, 0x48, 0xf4, 0x13, 0xcf, 0xc2, 0x68, 0x1f, 0x9a, 0xa1,
	0x6f, 0x19, 0x14, 0x73, 0x70, 0xb4, 0xd7, 0x4b, 0x3c, 0xff, 0x41, 0x14, 0x67, 0x6c, 0xbe, 0xe5,
	0x8b, 0x07, 0xd0, 0xa0, 0x95, 0xa7, 0xa6, 0xa8, 0x0b, 0x8a, 0x35, 0xd2, 0x27, 0xc4, 0xee, 0x45,
	0xdc, 0x0a, 0xe7, 0x82, 0x35, 0xba, 0x20, 0x76, 0xaf, 0x84, 0x19, 0x42, 0x2b, 0x4f, 0x51, 0xd1,
	0x13, 0x58, 0xf7, 0x09, 0xd6, 0x27, 0x98, 0x10, 0xc3, 0x8e, 0x5f, 0x14, 0xf8, 0x04, 0x5f, 0x44,
	0x11, 0xb4, 0x03, 0x0d, 0x96, 0x10, 0x60, 0xe2, 0x47, 0x5d, 0xa3, 0xe9, 0x59, 0x95, 0x86, 0x89,
	0x5f, 0xd2, 0xf6, 0xef, 0x0a, 0xb4, 0x73, 0x85, 0x97, 0x1d, 0x10, 0x12, 0x8d, 0xa7, 0x3b, 0x96,
	0x18, 0xa5, 0x2e, 0x22, 0x67, 0x16, 0x7a, 0xc4, 0x7e, 0xd6, 0xa3, 0x71, 0x0f, 0xe3, 0x13, 0x42,
	0xf0, 0x4b, 0x36, 0xeb, 0x21, 0xda, 0x83, 0x8d, 0xd9, 0xaf, 0x47, 0xc9, 0x4d, 0x56, 0x44, 0xca,
	0x51, 0xc9, 0xba, 0x5e, 0xc3, 0x66, 0x8e, 0x7c, 0x97, 0x2d, 0x6a, 0x31, 0xef, 0x39, 0xbf, 0xe5,
	0x49, 0x15, 0x2f, 0x48, 0x3e, 0x82, 0xcf, 0x16, 0x28, 0x75, 0x41, 0xd1, 0x15, 0x6c, 0xe6, 0x28,
	0x31, 0xfa, 0x12, 0x36, 0xee, 0x58, 0x4c, 0x1f, 0x3b, 0x84, 0xc6, 0xc7, 0x82, 0x15, 0x36, 0xee,
	0x92, 0xfc, 0x02, 0xf0, 0x8f, 0xd0, 0x2d, 0x13, 0xe2, 0x82, 0xea, 0x3f, 0xe0, 0x69, 0xa9, 0xa2,
	0xb2, 0x97, 0x39, 0xd5, 0x6d, 0x16, 0x89, 0xb6, 0x95, 0x11, 0x6a, 0x53, 0xd1, 0x63, 0x31, 0x7c,
	0xe7, 0x4f, 0x04, 0x35, 0x76, 0xc8, 0x3c, 0x97, 0x60, 0xf4, 0x32, 0x65, 0xd6, 0x88, 0x30, 0x6b,
	0xdd, 0x58, 0xdd, 0xa3, 0xac, 0xa4, 0x5b, 0x8b, 0x22, 0x29, 0xbb, 0x46, 0xd0, 0x71, 0xd2, 0xae,
	0x11, 0x61, 0xd7, 0x9e, 0x48, 0x90, 0xb9, 0x60, 0x0b, 0x46, 0xb2, 0x06, 0x5d, 0x48, 0x86, 0x8d,
	0x08, 0xc3, 0xb6, 0x97, 0xa5, 0xa4, 0x84, 0x51, 0xb0, 0xa4, 0x62, 0x74, 0x99, 0xb2, 0x6c, 0x44,
	0x58, 0xb6, 0x6f, 0x24, 0xd8, 0x22, 0x41, 0x8b, 0x87, 0x4c, 0x22, 0xd0, 0xdb, 0x8c, 0x69, 0x23,
	0xc2, 0xb4, 0x3d, 0x93, 0xb0, 0x92, 0xce, 0x08, 0x5a, 0xa6, 0x9a, 0x11, 0x25, 0xeb, 0x45, 0x84,
	0x6d, 0x7b, 0x96, 0x79, 0x01, 0xe9, 0x34, 0x41, 0x94, 0xab, 0xd1, 0x20, 0x6b, 0xdc, 0x88, 0x30,
	0x6e, 0xf2, 0x46, 0xca, 0x02, 0x22, 0x98, 0xd9, 0x7a, 0x74, 0x21, 0x5b, 0x37, 0x22, 0xac, 0xdb,
	0xae, 0x3c, 0x77, 0x3a, 0x2b, 0x02, 0xca, 0xb5, 0xe2, 0xb0, 0x88, 0x5b, 0x4d, 0x84, 0x79, 0xcb,
	0x39, 0x2c, 0x71, 0xc6, 0xfc, 0xb0, 0xc4, 0x11, 0xf4, 0x3e, 0xcf, 0xbe, 0x11, 0x61, 0xdf, 0xbe,
	0xca, 0xa2, 0xe4, 0xcc, 0x08, 0x99, 0xc7, 0x60, 0xc3, 0xa6, 0x6d, 0x18, 0x11, 0x06, 0x6e, 0xb7,
	0x00, 0x3b, 0x1f, 0x56, 0xaa, 0x45, 0xb4, 0xd0, 0xc2, 0x11, 0x61, 0xe1, 0x5e, 0x48, 0xec, 0x02,
	0xe9, 0x10, 0x8d, 0x0a, 0xa9, 0xe8, 0xae, 0xd8, 0xc4, 0x11, 0x61, 0xe2, 0x7a, 0xd9, 0xb6, 0x8b,
	0x6b, 0xa2, 0xbe, 0xc5, 0x5c, 0x75, 0x08, 0x0f, 0x33, 0x5a, 0x81, 0x9e, 0x40, 0x1d, 0xc7, 0x9f,
	0xf2, 0x48, 0xfe, 0x7f, 0xa8, 0xf4, 0xb4, 0x79, 0x0c, 0x3d, 0x06, 0xa0, 0x46, 0x60, 0x63, 0xca,
	0x3e, 0xe3, 0x5c, 0x3d, 0x14, 0x2d, 0x11, 0x41, 0x4d, 0x58, 0xb2, 0xb9, 0x45, 0x63, 0x3f, 0xb0,
	0x7f, 0xd5, 0x21, 0x34, 0x65, 0x39, 0x29, 0x6f, 0xd3, 0x82, 0x15, 0xee, 0xfb, 0x44, 0x87, 0xe8,
	0x21, 0x6d, 0xd2, 0xa2, 0x16, 0x33, 0x93, 0xa6, 0xbe, 0x81, 0xad, 0x7c, 0xc1, 0xb9, 0x57, 0x37,
	0xca, 0x2a, 0xe2, 0x6e, 0xfc, 0x41, 0x25, 0xf0, 0xb8, 0x58, 0x74, 0xca, 0xc1, 0x2f, 0xa0, 0x35,
	0xf3, 0x59, 0x09, 0x57, 0x24, 0xfa, 0xa0, 0xf8, 0xb7, 0x5f, 0x67, 0xc6, 0x48, 0x0d, 0xa1, 0x9d,
	0x2b, 0x49, 0xe5, 0xbd, 0xd2, 0x9f, 0xee, 0x2a, 0xff, 0x90, 0x2c, 0xf0, 0x13, 0xbd, 0x78, 0xf3,
	0x84, 0x59, 0xe8, 0xa9, 0xef, 0xa1, 0x9d, 0xab, 0x5b, 0xe5, 0x6d, 0x25, 0xff, 0x24, 0x4e, 0xc4,
	0xdc, 0x3f, 0xa9, 0x57, 0xb0, 0x95, 0xaf, 0x5f, 0xe5, 0xec, 0xe4, 0x9a, 0x8f, 0x04, 0x3a, 0x5e,
	0xf3, 0x91, 0xfa, 0x3d, 0xb4, 0xf2, 0x54, 0xac, 0x14, 0xab, 0xfe, 0xc2, 0x4f, 0x64, 0x4a, 0xb3,
	0xca, 0xd7, 0xd2, 0x86, 0x55, 0x9f, 0xe8, 0xa6, 0xe1, 0xf3, 0x75, 0x2c, 0x6b, 0x2b, 0x3e, 0xab,
	0x57, 0x4d, 0xe8, 0x2c, 0x12, 0xad, 0x72, 0x66, 0x8e, 0x77, 0xa9, 0xe6, 0x78, 0x17, 0xf5, 0x37,
	0x68, 0xe5, 0x49, 0xd8, 0xbd, 0xce, 0xc4, 0xbc, 0x81, 0xd8, 0xc0, 0xfa, 0x8c, 0xad, 0x5e, 0x73,
	0xef, 0x52, 0x2c, 0x5f, 0xf7, 0x7a, 0x4b, 0x09, 0x73, 0x53, 0x4d, 0x9b, 0x1b, 0xb5, 0x0f, 0x3b,
	0xe5, 0x5a, 0x55, 0xda, 0xe4, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x99, 0x2e, 0x35, 0xce,
	0x12, 0x00, 0x00,
}
