FROM tozd/sgx:ubuntu-bionic

ARG EKIDEN_COMMIT_SHA
ARG EKIDEN_BUILD_IMAGE_TAG

LABEL com.oasislabs.ekiden-commit-sha="${EKIDEN_COMMIT_SHA}"
LABEL com.oasislabs.ekiden-build-image-tag="${EKIDEN_BUILD_IMAGE_TAG}"

ENV PATH="/ekiden/bin:${PATH}"

ADD . /ekiden

RUN apt-get install -qq libsnappy1v5 librocksdb5.8
