FROM tozd/sgx:ubuntu-bionic

ARG EKIDEN_COMMIT_SHA

LABEL com.oasislabs.ekiden-commit-sha="${EKIDEN_COMMIT_SHA}"

ENV PATH="/ekiden/bin:${PATH}"

ADD . /ekiden

RUN apt-get install -qq libsnappy1v5 librocksdb5.8
